### ISSUE TITLE
Switch from HTML to Markdown

### ISSUE THREAD

**Issue by IvanSanchez** [artemis-nerds/protocol-docs#1]
I'd like to see the documentation written in markdown - right now it is messy to edit tables.

This would require moving `index.html` to `index.md` and start cleaning out the tables and lists that need attention.

**Comment by rjwut** [comment]
The principal reason I wanted to move away from Markdown was because there was no support for tables. I'm willing to entertain the idea, but I personally feel that tables make some things in the documentation better.

Do you have specific examples of why using tables make things more difficult?

**Comment by mrfishie** [comment]
You can do [tables in Github-flavoured markdown](https://help.github.com/articles/github-flavored-markdown/#tables).. perhaps using a wiki would be the best way to organise everything?
