### ISSUE TITLE
 0x4c821d3c:0x1f seems to be fighter shooting

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#102]
Packet type 0x4c821d3c "valueInt" [from CLIENT]
SubType 0x1f "FighterShootPacket"
Shooter (int) Shooting Ship ID (the fighter that is shooting)
Shot (int) Shot Ship ID (who the fighter is shooting)

**Comment by NoseyNick** [comment]
Honestly this one is pretty complete, not sure what other details we could realistically add to this one?

**Comment by rjwut** [comment]
Well, the title said "seems to be" which indicates uncertainty. If that's not the case, feel free to change the tags.

**Comment by NoseyNick** [comment]
Not sure I have permission to do tags? I may be wrong?

**Comment by rjwut** [comment]
Any idea when this packet came into existence? Perhaps when fighters were introduced?

**Comment by NoseyNick** [comment]
Great question! Unfortunately I have WAY more server2client data than client2server, so can't easily confirm. I can confirm:
195 v2.2.0 games I never saw the above FighterShoot packet
5 v2.3.0 games - this was when fighters were introduced BUT I don't think I have ever MitM a fighter
4 v2.4.0 games, ditto
1 v 2.5.1 game, ditto
v2.6.0 I started to see them, plenty of them.

I'll try to MitM a fighter in 2.3.0 if you wish.

**Comment by NoseyNick** [comment]
Tried to confirm for you, but I'm tripping over the big valueInt subtype renumbering discussed in  https://github.com/artemis-nerds/protocol-docs/issues/78 and https://github.com/artemis-nerds/protocol-docs/pull/87 and my parser is pretty terrible at handling that right now   :disappointed: 

I'm PRETTY sure 2.2.0 has:
0x4c821d3c:0x1d fighter launch
0x0351a5ac:0x07 fighter pilot X/Y/Z/etc
0x4c821d3c:0x1e fighter shoot (as above, TBC)
0x4c821d3c:0x07 fighter request dock

I'l fix up later and re-confirm the full set of params.

**Comment by rjwut** [comment]
@NoseyNick I'm adding this into the docs, but I would still like a confirmation of the version if you can.

**Comment by NoseyNick** [comment]
As discussed on Discord, and as seen in http://noseynick.org/artemis/parser.pl ...

I can't go back earlier than 2.0.0.
In 2.0.0, subtypes 0x00 HelmSetWarp to 0x1b ClimbDive exist

2.1.5 moves ClimbDive to 0x1c. Not clear if anything else has replaced it on 0x1b

2.3.0 introduces 0x1d FighterLaunch and 0x1e FighterShoot

Some beta around 2.3.109 is "the big renumbering" (just before 2.4.0)...
0x16 becomes unused (as far as I can tell? please prove me wrong! :laughing: )
0x17 (prev EngResetCoolant) is the new improved SetShipSettings (which includes accent hue)
0x18 (prev HelmToggleReverse) is the new EngResetCoolant
0x19 (prev RequestFullUpdate) is the new HelmToggleReverse
0x1a (prev TogglePerspective) is the new RequestFullUpdate
0x1b (prev ClimbDive then unknown/unused since 2.1.5) is now TogglePerspective
0x1c (prev ClimbDive) is now unknown/unused
0x1d (prev FighterLaunch) is now ClimbDive
0x1e (prev FighterShoot) is now FighterLaunch
0x1f (prev unused?) is now FighterShoot
0x20 is introduced - EmergencyJump (one int param: 0=forward 1=backward)

2.5.106 (just before 2.6) introduces 0x21 SingleSeatSelect

2.6.204 (just before 2.7) introduces 0x22 BioBeaconControl

**Comment by NoseyNick** [comment]
Or to put it the other way...

Everything up to and including ButtonClick 0x15 since 2.0.0 (I think? or earlier?)

SetShipSettings 0x16 until 2.3.109/2.4.0 moved it to 0x17 and added accenthue
EngResetCoolant 0x17 until 2.3.109/2.4.0 moved it to 0x18
HelmToggleReverse 0x18 until 2.3.109/2.4.0 moved it to 0x19
RequestFullUpdate 0x19 until 2.3.109/2.4.0 moved it to 0x1a
TogglePerspective 0x1a until 2.3.109/2.4.0 moved it to 0x1b
ClimbDive 0x1b until 2.1.5 moved it to 0x1c, and 2.3.109/2.4.0 moved it to 0x1d
FighterLaunch 0x1d from introduction in 2.3.0 until 2.3.109/2.4.0 moved it to 0x1e
FighterShoot 0x1e from introduction in 2.3.0 until 2.3.109/2.4.0 moved it to 0x1f
EmergencyJump 0x20 introduced in 2.3.109/2.4.0
SingleSeatSelect 0x21 introduced in 2.5.106/2.6
BioBeaconControl 0x22 introduced in 2.6.204/2.7

An interesting gap at 0x1b introduced in 2.1.5 when ClimbDive moved up one. 2.3.109/2.4.0 moved it to 0x1c

2.3.109/2.4.0 also introduced another interesting gap at 0x16 when SetShipSettings moved up one (and upgraded).
