### ISSUE TITLE
0xf754c8fe:0x19 Unknown

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#105]
Single int payload. values of 4, 3, 2, 0 observed in the wild. Purpose unknown.

**Comment by NoseyNick** [comment]
0xf754c8fe is simpleEvent
Subtype 0x19
Unknown Integer

Values 2 and 3 are pretty damned rare. 0 is "normal", 4 is "not unusual":
```
    429 Unknown_f754c8fe_19(0);
      1 Unknown_f754c8fe_19(2);
      1 Unknown_f754c8fe_19(3);
     84 Unknown_f754c8fe_19(4);
```

captures/artemis-2018-01-17.2326.01s.xz has all 4 values:
```
Unknown_f754c8fe_19(0); # shortly after the start of the game SkyBox() startGame() etc
Unknown_f754c8fe_19(4); # shortly after a player ship was destroyed?
Unknown_f754c8fe_19(3); # dunno, looks to be mid-battle though?
Unknown_f754c8fe_19(2); # also mid-battle?
```

Injecting it via the DISCO server has no obvious visible or audible effect.

**Comment by StarryWisdom** [comment]
small recording I had
Unknown_f754c8fe_19(4);
objectDelete(ObjAsteroid(1751));
I assume that one was relating to a biomech eating a asteroid?

later - or maybe a blackhole eating an asteroid?

**Comment by StarryWisdom** [comment]
silly question (and makes little sense) is it biomech related - they eat 4 things before growing dont they? (does this packet appear more in that huge biomech have taken over the system capture?)

**Comment by NoseyNick** [comment]
There's no objectIDs though, nor X/Y/Z coords, so it's presumably not a graphical effect at particular coords, nor for a particular object, nor is it telling you WHICH asteroid got eaten, nor WHICH biomech/blackhole did the eating.

Is there... an asteroid-eating sound-effect or something that's not using the 0xf754c8fe:0x03 SoundEffectPacket? Or a blackhole-swallowing sound? Or a "something just got swallowed by a blackhole" graphical effect that needs no coords? (similar to a damageShake)?

I think you just confused me more, @StarryWisdom   :laughing:

**Comment by StarryWisdom** [comment]
value of 0 makes side!=player side biomechs appear orange
value of !=0 makes them red
reason for 2, 3 or 4 is as yet unknown
requesting dump info from nick on discord
will look later at above replay for more info

**Comment by NoseyNick** [comment]
As posted on Discord, my grand totals are...
```
429 Unknown_f754c8fe_19(0);
  1 Unknown_f754c8fe_19(2);
  1 Unknown_f754c8fe_19(3);
 84 Unknown_f754c8fe_19(4);
```
There's ONE game where values 2 and 3 occurred, specifically...
```
      1 Unknown_f754c8fe_19(0);
    593 heartbeat();
      1 Unknown_f754c8fe_19(4);
      5 heartbeat();
      1 Unknown_f754c8fe_19(3);
     51 heartbeat();
      1 Unknown_f754c8fe_19(2);
      5 heartbeat();
```
Doesn't LOOK like Biomechs gradually forgiving? Could it be other "sides" declaring war in some way? Biomechs are side 30 though right?
:confused:

**Comment by NoseyNick** [comment]
Think I'll close this in favour of the newer, more detailed, #198
