### ISSUE TITLE
List of Artemis libraries

### ISSUE THREAD

**Issue by mrfishie** [artemis-nerds/protocol-docs#11]
Partially in response to https://github.com/artemis-nerds/protocol-docs/issues/9#issuecomment-155967415, where @dthaler wrote

> Just in case you're keeping track of Artemis network libraries in other languages, I have one in C++ that is used by Artemis DMX Tools. This documentation project has been extremely valuable.

Both @NoseyNick and @dthaler have said that they are working on Artemis clients, and I think it'd be awesome if we could keep track of a list of libraries made by the community, by-language, with links to where they can be found. So, we need a list of projects, and also need to decide if this list should go in this documentation, or in a separate repository. If in this documentation, it might be worth re-structuring the document a little bit to allow us to add different types of Artemis-related content in the future, rather than _just_ protocol documentation.

**Comment by mrfishie** [comment]
Oops.. that was weird. Just ignore that, @rjwut...

**Comment by NoseyNick** [comment]
@NoseyNick, Perl, not yet fit for public consumption. Tonnes of ugly pack()/unpack(), and definitely deserves a neater OO rewrite.

**Comment by rjwut** [comment]
Let's gather the links here in the comments, then I'll put something together for the documentation.

C++: (link?)
Go: **[huin/artemis](https://github.com/huin/artemis)**
Java: **[ArtClientLib](https://github.com/rjwut/ArtClientLib)**
Node.js: **[node-asbs-lib](https://github.com/artemis-nerds/node-asbs-lib)**
...others?

**Comment by mrfishie** [comment]
As far as I know, the C++ library @dthaler was talking about is part of [Artemis DMX Tools](http://www.armidalesoftware.com/Artemis/DMXTools.htm), which doesn't appear to be open source, but we could still link to it.

Also, do we want to consider listing other tools as well (not just libraries)?

**Comment by mrfishie** [comment]
[Here's](https://github.com/prophile/libdiana) an Artemis Python library... Not sure how complete it is, or if its still maintained at all.

**Comment by NoseyNick** [comment]
Think I'm ready to admit that http://noseynick.org/artemis/ exists - bunch of mostly-Perl Artemis tools including my parser.pl which can turn various raw TCP / hex / xz / gz Artemis captures into somewhat human-readable perl which, when run, re-creates the same raw binary. Includes a few tools to help capture raw data, and of course the Artemis DISCO server everyone has been waiting for since they introduced Accent color / hue  😉
