### ISSUE TITLE
2.7.0 UDP LAN server discovery broadcasts

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#116]
Clients on the "connect to server" screen periodically broadcast from a random ("ephemeral") UDP port to 255.255.255.255 port 3100, the single byte `0x05`, which we assume means "Are there any servers here?"

Servers, listening on UDP 3100, respond from their IP (port 3100) back to the client IP (ephemeral port), unicast:
`0x06` (which we assume means "I am a server, with IP and name...")
`0xNN00` (little-endian length of...)
`"192.168.1.100"` (or whatever your server IP is, in plain 8-bit ASCII not Artemis's usual UTF16, not `\0`-terminated)
`0xNN00` (length of...)
`"user\0"` (server / user name, plain 8-bit ASCII, `\0`-terminated)

### Example:
```
192.168.1.145:38331 > 255.255.255.255:3100: UDP, length 1
05

192.168.1.198:3100 > 192.168.1.145:38331: UDP, length 23
06 0d 00 31 39 32 2e 31 36 38 2e 31 2e 31 39 38 05 00 6e 69 63 6b 00
   <len>  1  9  2  .  1  6  8  .  1  .  1  9  8 <len>  n  i  c  k \0
```

**Comment by NoseyNick** [comment]
\05 is sometimes known as ASCII "ENQ" (enquiry)
\06 is sometimes known as ASCII "ACK" (acknowledgement), so I assume...
```
192.168.1.145:38331 > 255.255.255.255:3100: UDP, length 1
05
ENQ

192.168.1.198:3100 > 192.168.1.145:38331: UDP, length 23
06  0d 00 31 39 32 2e 31 36 38 2e 31 2e 31 39 38 05 00 6e 69 63 6b 00
ACK <len>  1  9  2  .  1  6  8  .  1  .  1  9  8 <len>  n  i  c  k \0
```

**Comment by NiKiZe** [comment]
I would assume server port number to be included as well?

**Comment by NoseyNick** [comment]
Not seen port number. Will confirm, but suspect it assumes networkPort=2010 or whatever you have in your artemis.ini

There seems to be no way to change the "3100" used for the UDP discovery broadcasts either.

... and the ephemeral port (38331 in the above examples) is essentially random, which may make firewalling tricky - you have to allow 3100 IN to your client, but that's 3100 on the FAR end, random port on YOUR end. Hopefully your firewall is intelligent enough to realise this is a reply to a broadcast to 255.255.255.255:3100. Mine isn't.   😞

**Comment by NoseyNick** [comment]
Confirmed: Port number is NOT sent over the UDP discovery protocol, regardless of default networkPort=2010 or (say) networkPort=2020

Clients will still attempt to connect on the networkPort specified in THEIR config file (or default 2010).

**Comment by rjwut** [comment]
I've reported this as a bug to Thom.

**Comment by JordanLongstaff** [comment]
I think there's more to broadcasting than simply sending a packet to 255.255.255.255. I've tried replicating this behaviour in my app, but I'm not getting any responses. Researching this brings up comments about broadcasting to the local network layer broadcast address, which is dependent on subnets, vs. 255.255.255.255 which is the "global" broadcast address. Here's a link with some detail: https://serverfault.com/questions/219764/255-255-255-255-vs-192-168-1-255

Does the server need to be set up to accept discovery broadcasts like this? If so, how? Does that have anything to do with what the server uses as the username field in the response?

**Comment by NoseyNick** [comment]
Hi @JordanLongstaff - depending on what language and what OS you're using, you may need some equivalent of http://www.microhowto.info/howto/send_a_udp_datagram_in_c.html#idp56384
```c
int broadcast=1;
setsockopt(fd,SOL_SOCKET,SO_BROADCAST, &broadcast,sizeof(broadcast));
[then send to 255.255.255.255]
```
https://demey.io/network-discovery-using-udp-broadcast/ has some Java code...
```java
c = new DatagramSocket();
c.setBroadcast(true);
[then send to 255.255.255.255]
```
Hope one of those helps?

**Comment by NoseyNick** [comment]
Oh and yes, host-based firewalls on either end COULD block the traffic. Presumably the client firewall needs to allow OUT to 255.255.255.255:3100 and IN any replies. The server firewall needs to allow IN from any IP + UDP port on the local subnet(s) to 255.255.255.255:3100 where it is listening.

**Comment by JordanLongstaff** [comment]
I am using Java. The Java code link you sent me mentions that sending to 255.255.255.255 is just one attempt; it also attempts to find other network interfaces on which to broadcast. Perhaps that is what I have to do. I don't like the idea of forcing users to configure their firewall to allow these UDP broadcasts specifically on 255.255.255.255.

**Comment by NoseyNick** [comment]
In theory 255.255.255.255 should work if you have 1 NIC with 1 IP on 1 LAN.
The "finding other network interfaces" thing sorta makes sense if you have a cellular IP, a WiFi IP, maybe also a wired Ethernet IP, or 2/3/4/5/N of the above... Otherwise "when you say broadcast, do you mean on ALL these NICs/modems?"
For Android, honestly not sure...
https://stackoverflow.com/questions/17308729/send-broadcast-udp-but-not-receive-it-on-other-android-devices
https://stackoverflow.com/questions/22296891/how-to-receive-udp-broadcasts-on-an-android-device
https://code.google.com/p/boxeeremote/wiki/AndroidUDP
https://gist.github.com/finnjohnsen/3654994
https://answers.unity.com/questions/250732/android-build-is-not-receiving-udp-broadcasts.html

IMHO Thom should have just had the server periodically broadcast to 255.255.255.255:3100 (say, every 5sec) and have clients listen for it... Or why reinvent the wheel when there's https://en.wikipedia.org/wiki/Multicast_DNS ? ... but in this repo, Thom is right, by definition   :grin:

**Comment by rjwut** [comment]
I'm writing the documentation for this, and will put 255.255.255.255 for now. If we settle on something else, I'll update it appropriately.

**Comment by NoseyNick** [comment]
255.255.255.255 was certainly what my official clients used to ENQ. My official servers ACK by unicast, exactly as described in my "Example" packet captures above.

Wireshark is your friend... Or not so much your friend, more that sensei you trust and respect deeply, but whom you dare not anger   :wink:

**Comment by JordanLongstaff** [comment]
Is there anything you can tell me about how long it takes for a server to be discovered via UDP? I've set the timeout in my app to be 10 seconds, but maybe that's not enough.

**Comment by NoseyNick** [comment]
Assuming you want to emulate the "official" client, when asking for a server IP/address, you should broadcast the probe "ENQ" packets approx every 2.62 seconds. When you receive an ACK (bear in mind you could receive MULTIPLE if you have multiple servers on your LAN) you should add a button on your screen with the server / user name for a simple 1-click-connect to that IP. As far as I can tell they "never" get removed until you quit, even if a server stops ACKing.
