### ISSUE TITLE
ReadyPacket2 believed to be "request for full EngGridUpdatePacket"

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#12]
When the client sends ReadyPacket2, the server seems to respond with a fully-populated EngGridUpdatePacket (AKA damConInfo in some libraries), enough to display the mini ship outline thingy with ALL the red damage dots on it, as seen in a corner of Main/Helm/Weapons/Data screens.

The "Unknown (byte) Values of 0 and 1 have been observed" first field in EngGridUpdatePacket then seems to correspond to 1="This is a fully-populated one you asked for with ReadyPacket2" vs 0="This is an unsolicited partial update" (0). The partial updates only indicate NEW/REPAIRED damage, MOVING damcon teams, etc.

Suggest ReadyPacket2 should then probably be renamed to "RequestFullEngGridUpdatePacket", or preferably something more catchy   ;-)

**Comment by dthaler** [comment]
I can confirm that whenever the client sends ReadyPacket2, the server results with EngGridUpdatePacket.  Hence I agree with the proposed renaming.  It has nothing to do with being Ready per se, it can be sent in the middle of a simulation.
