### ISSUE TITLE
A note about "DifficultyPacket" 0x3de66711 = JamCRC("startGame")

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#126]
`startGame(level, gametype)` appears to be pretty much required.
If you \<cough\>Starry@USN\</cough\> create a server which does NOT send this packet, you'll find ships have no beam arcs on Helm/Weapons screens. Hypothesis is that Thom's code has something like:
```
BeamRange=0
when startGame packet received:
  if level <11 then BeamRange=something
  else BeamRange=something_else
```
Confirmed by myself - my `parser.pl` is quite good at creating code for a replay of (bits of) a previous capture, and then it's easy to edit that skeleton, remove `startGame(...)` and observe the effects.

**Comment by rjwut** [comment]
Renaming to GameStartPacket.
