### ISSUE TITLE
Player ship properties error somewhere around "In a nebula"

### ISSUE THREAD

**Issue by JordanLongstaff** [artemis-nerds/protocol-docs#127]
I parsed two different ObjectUpdatePackets, both for the player ship Artemis. The first had a two-byte field right before the "name" field, which corresponds to what the docs say is a two-byte Boolean field for the ship being in a nebula.

In the second packet, however, there was only one byte before the "name" field. Strangely, the bit field doesn't suggest that any property fields around this spot in the payload were omitted. So, it's like the nebula field is sometimes one byte long and sometimes two?

I checked the preceding fields, like "heading" and "velocity", and they were correct in both packets.

**Comment by NoseyNick** [comment]
Indeed, see  #118 ... specifically:
PlayerShip "In a nebula (bit 3.3, boolean, 2 bytes)" becomes "In a nebula (bit 3.3, boolean, byte)"
[...]
PlayerShip "In a nebula (bit 3.3, boolean, byte)" tells you which "nebType" you are in (1,2,3) or 0 for "not in a nebula". Apart from the fact that 3 nebTypes exist, there seems to be no notable difference between them from a game mechanics perspective, they all limit you to warp1. Scripting may (ab)use the different types for story purposes.

Assume your 2-byte booleans were from v2.6.X or before, and your 1-byte ones were v2.7.X?
