### ISSUE TITLE
Note that UTF16 strings can contain NULLs

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#13]
Smells like a bug in the server / protocol, but worth noting, perhaps in https://artemis-nerds.github.io/protocol-docs/#string-format
The UTF16 strings can contain NULLs (0x0000) in the middle of the strings. When playing 'border war' I get a CommsIncoming message, priority 0, length 0x0d (=13), (16-bit) chars "TSNCOM\0eeeee\0". The 209-char message is "This is an official WAR WARNING!  Enemy fleets are massing in the next sector.  Expect an invasion soon.\0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\0". I had previously naively been hoping I could skip the length int and start reading 16-bit chars until I hit 0x0000. It turns out this is USUALLY but not ALWAYS true   :-(

**Comment by rjwut** [comment]
The documentation that you linked to already says this: "Under normal circumstances, the null character would be the last two bytes read for the string; if the null character occurs earlier, the remaining bytes are meaningless and should be discarded."

**Comment by NoseyNick** [comment]
Mmmmm, 'K, granted. inattention on my part then   :-)
