### ISSUE TITLE
correction for single & double scaning npc(4.1,4.2)

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#134]
as a single scan is done within visual range biomechs do single scans (as can be observed via the number of single scans filled with 0x400000??) - double scans they don't do obviously

**Comment by NoseyNick** [comment]
I have definitely seen DoubleScan filled with 0x40000000:
```
# STAT:   86070   NPCShip.DoubleScan (min 0 max 1073741828)
# STAT:   19387     NPCShip.DoubleScan = 0 (0x0)
# STAT:    2528     NPCShip.DoubleScan = 1073741824 (0x40000000)
# STAT:     126     NPCShip.DoubleScan = 1073741828 (0x40000004)
# STAT:   54941     NPCShip.DoubleScan = 2 (0x2)
# STAT:    3845     NPCShip.DoubleScan = 4 (0x4)
# STAT:    5219     NPCShip.DoubleScan = 6 (0x6)
# STAT:      24     NPCShip.DoubleScan = 8 (0x8)
```

**Comment by rjwut** [comment]
Rather than make assertions we are unsure about, I'll simply remove any commentary from the documentation about whether or not biomechs do scans.
