### ISSUE TITLE
nebulas colors (1.4-1.6)

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#139]
as of 2.6 I was unable to convince any nebula to spawn in with a different color - this may of changed in 2.7 add into that the stock server giving slightly odd values in 1.4-1.6 it seems its probably not color?

**Comment by NoseyNick** [comment]
### Object Type 0x0a Nebula
  X (bit 1.1, float)
  Y (bit 1.2, float)
  Z (bit 1.3, float)
  R (bit 1.4, float)
  G (bit 1.5, float)
  B (bit 1.6, float)
  nebType (bit 1.7, byte, new in v2.7.0)

R/G/B are definitely R/G/B when seen on the 3D screens.
nebType seems to be 1=purple (#32004c), 2=cyan-ish (#00324c), 3=yellow (#32321a) when seen on 2D maps (LRS/sci/etc)

EG point your v2.7.1 client at the new improved "disco server" on noseynick.net
Source is at http://noseynick.net/artemis/disco-server.pl
You have red/green/blue throbby clouds on MainScreen/Observ. LRS shows fixed nebType 1/2/3

**Comment by StarryWisdom** [comment]
oh ... R G B is mainscreen color - not sci map color - I never thought of testing that (related - could we document its main screen color)

agree on the suggested change of flavor to nebType - it matches the mission scripting document flavor was somewhere semi official but not as official as that
