### ISSUE TITLE
0x4c821d3c:0x17 does exist

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#14]
Packet 0x4c821d3c subtype 0x17 DOES exist. Client to server (I'm going to GUESS Engineering, maybe Science console), no payload (apart from the type+subtype).
Have absolutely NO IDEA how to recreate it. Will hack around   :-(

**Comment by NoseyNick** [comment]
0000000 ef be ad de 1c 00 00 00 02 00 00 00 00 00 00 00
0000020 08 00 00 00 3c 1d 82 4c 17 00 00 00

**Comment by chrivers** [comment]
In fact, I have it logged in my "badpackets" list, too. I got exactly the same payload as you

3c1d824c17000000

Unfortunately, I also have no information about it, so far. But I've also only seen it with this payload

**Comment by rjwut** [comment]
Let's be sure to include this packet in the packet type reorganization.
