### ISSUE TITLE
emergency jump pc (6.3)

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#140]
quick testing implied pc 6.3 is an emergency/combat jump countdown, confirmation should be simple + min/max ranges

**Comment by NoseyNick** [comment]
See also https://github.com/artemis-nerds/protocol-docs/issues/130 for naming discussion. I call it  "EmergencyJump" but could rename "CombatJump" if I'm outvoted. I can't find EITHER in `changes.txt`, `mission-file-docs.txt`, `dat/vesselData.xml`, or even strings in `Artemis.exe` itself   :confused: 

Range seems to be 0.0 (ready to jump) to 1.0 (you just jumped), then trickling back down to 0.0 again

**Comment by StarryWisdom** [comment]
what was it called when it was introduced in the 2.4? time frame (wasnt playing then)

**Comment by NoseyNick** [comment]
2.3.109 I think (so 2.4 major release, sure). That's the problem, it was never really documented in changes.txt or anywhere else as far as I can tell   :confused:

**Comment by NoseyNick** [comment]
I've heard players call it "Emergency Jump", "Combat Jump", or even "5k Jump" (which I'm not sure is quite right anyway)   :man_shrugging:
