### ISSUE TITLE
EngGridUpdatePacket / shipSystemSync minor corrections

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#141]
if given 2 full status=true packets in a short time they turn into delta packets - I'm guessing its reset once per frame/ per network update speed but have not confirmed.

also (Is there an upper limit to this value?) - there are at least 2
above 100000% as soon as a damcon starts repairing it will jump to 99999%
above (signed 32 bit int max) % the number will wrap to negative, clearly the float is converted to a signed int before being displayed

**Comment by rjwut** [comment]
Fixed in a previous commit.
