### ISSUE TITLE
servers without heartbeats

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#144]
heartbeat is not required for an artemis client to behave correctly.
It seems the following things are controlled via hearbeats / object updates

objectUpdates - the yellow bar showing the disconnection statue
hearbeats - the thing saying server is running / not running

suggested correction
s/If a client does not receive a heartbeat packet within a reasonable amount of time, it can assume that the server is not functioning. /If a stock client doesn't receive a heartbeat regularly it will display simulation not running even though it will continue to behave correctly in other regards/

maybe change the word stock? not sure what to though

**Comment by NoseyNick** [comment]
I am definitely NOT voting for "authorized game client" even if the plainTextGreeting says "You have connected to Thom Robertson's Artemis Bridge Simulator.  Please connect with an authorized game client."   :laughing:

**Comment by NoseyNick** [comment]
Server could be "functioning", but not playing a game - "simulation not running".

II find hearbeats useful to tell me how much of a game I captured. If the GameOverStats say GameOverStat(0, 20, UTF16("Mission duration ( minutes )"))) but I only captured 200 heartbeats, 200*3sec = 600sec = 10mins, I know I only captured about half the game.

**Comment by rjwut** [comment]
Where exactly does the client say the simulation is not running if it doesn't get heartbeats?

**Comment by NoseyNick** [comment]
Main "console choice" screen. Top right. Was bottom-left on older versions.
