### ISSUE TITLE
Player Ship bit 5.5 is climb/dive

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#146]
Player Ship includes...
Unknown (bit 5.5, float)    "Usually 0.0, though -1.0 has been observed."

```pl
ObjPlayerShip(1019,[...],Unknown55=>0,[...]),# full
ClimbDive(-1); # from helm
ObjPlayerShip(1019,[...],Unknown55=>-1),
ClimbDive(1); # from helm
ObjPlayerShip(1019,[...],Unknown55=>0),
ClimbDive(1); # from helm
ObjPlayerShip(1019,[...],Unknown55=>1),
ClimbDive(1); # from helm
ClimbDive(-1); # from helm
ObjPlayerShip(1019,[...],Unknown55=>0),
ClimbDive(-1); # from helm
ClimbDive(-1); # from helm
ObjPlayerShip(1019,[...],Unknown55=>-1),
ClimbDive(1); # from helm
ObjPlayerShip(1019,[...],Unknown55=>0),
```
As I'm sure you remember, clicking "climb" will leave you climbing (-1) until you press "dive" to stop it and return to neutral (0). Clicking "dive" will leave you diving (+1) until you click "climb" to return to neutral (0). 

I've definitely seen some more "analogue" values as well though, perhaps when an analogue joystick is being used?

**Comment by NoseyNick** [comment]
This... isn't the same as "Pitch" though. Hmmmm.

**Comment by NoseyNick** [comment]
OK, this seems to be sorta setting a "target pitch" of 0.1921150 * Unknown55
If Helm asks the ship to climb (-1) then Unknown55 will be set to -1, and Pitch will "tend towards" -0.1921150.
If you tap "dive" you'll set Unknown55 to 0, and Pitch will "tend towards" 0 (perhaps "only" getting as close as -2.8E-44 but hey that's close).
Hit "dive" again, Unknown55 will go to 1, and Pitch will "tend towards" 0.1921150.

**Comment by JordanLongstaff** [comment]
I think the "target pitch" varies based on the ship's maneuverability. The amount of power that Engineering directs to the Maneuver system affects how fast the ship can climb/dive.
