### ISSUE TITLE
Name of typhon in v2.6

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#148]
creature type 0x00  - typhon in version 2.6 or less was just called a ZZ (even after a scan) the typhon name only came in v2.7, should the table be updated to be

0x00 | ZZ | typhon | a.k.a. classic space monster or crystalline entity
0x01 | whale | whale
.....

**Comment by rjwut** [comment]
The table was intended to simply indicate which type of monster each value represented. I don't want people to think that "ZZ" and "typhon" are different creature types. So I'll put a note that explains this above the table and leave the table as is.
