### ISSUE TITLE
Packet 0xf754c8fe subtype 0x13 Unknown, Detonation-related?

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#15]
I have packet captures with a bunch of undocumented packet 0xf754c8fe subtype 0x13 (int usuallySeven, int objID). Seems to happen immediately before DestroyObject(Mine, objID) or DestroyObject(Torpedo, objID). I'm not sure what "usuallySeven" is except that it's usually 0x07. Does NOT seem to correspond to ObjectType 'cos it's 0x07 for both Mines or Torpedos. Will see if I can recreate sometime. In the meantime I am calling it UnknownMaybeDetonatePacket. Anyone have better details?
[moving to separate issue]

**Comment by rjwut** [comment]
Could you include packet dumps, especially at least one for each distinct value of usuallySeven?

**Comment by NoseyNick** [comment]
0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 13 00 00 00 07 00 00 00
0000040 5c 05 00 00

0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 13 00 00 00 07 00 00 00
0000040 f4 08 00 00

0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 13 00 00 00 07 00 00 00
0000040 a9 09 00 00

0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 13 00 00 00 07 00 00 00
0000040 db 09 00 00

0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 13 00 00 00 07 00 00 00
0000040 32 0a 00 00

I called it "usuallySeven" because it has always been 7 in any packet I have captured, but it seems like an unlikely padding value, probably has SOME significance, may not ALWAYS be 7?
The objectIDs above correspond to a mixture of Torpedos and mines, destroyed in the very next packet. like:

0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 13 00 00 00 07 00 00 00
0000040 c0 06 00 00 ef be ad de 1d 00 00 00 01 00 00 00
0000060 00 00 00 00 09 00 00 00 30 3e 5a cc 0b c0 06 00
0000100 00
