### ISSUE TITLE
dat/base-plans.txt

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#151]
This file seems to have existed since 2.3.0.
It looks like it MIGHT be something about how to lay minefields near bases or something?
Anyone able to confirm **IF** it's used, and **HOW** it's used? If so, presumably worth documenting, somewhat like how .SNT files are documented even if they're not a "protocol" as such.

**Comment by NoseyNick** [comment]
```
strings -el ArtemisVer/2.7.1/Artemis.exe | egrep -i base-plans
strings ArtemisVer/2.7.1/Artemis.exe | egrep -i base-plans
```
No results from either. For comparison, vesselData.dat **does** show up (both UTF16 and UTF8/ASCII).

base-plans.txt be a red-herring, something Thom started on, never finished, but left around?

**Comment by rjwut** [comment]
[This forum thread](https://artemis.forumchitchat.com/post/baseplans-txt-7934715?trail=30) indicates that `base-plans.txt` was indeed for laying mine fields around bases, but it appears to be a feature that Thom has abandoned.

**Comment by NoseyNick** [comment]
I guess that wraps it up, thanks @rjwut
