### ISSUE TITLE
unknown pc (bit 5.7, int)

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#157]
while not confirmed this sounds a lot like the zetroth scan bitmap / map visability - I can test this within a few weeks

**Comment by NoseyNick** [comment]
Certainly plausible:
```
# STAT:   52554   PlayerShip.Unknown57 (min 0 max 4294967295)
# STAT:    2891     PlayerShip.Unknown57 = 0 (0x0)
# STAT:    3817     PlayerShip.Unknown57 = 4 (0x4)
# STAT:    3510     PlayerShip.Unknown57 = 6 (0x6)
# STAT:      28     PlayerShip.Unknown57 = 12 (0xc)
# STAT:      21     PlayerShip.Unknown57 = 14 (0xe)
# STAT:       1     PlayerShip.Unknown57 = 20 (0x14)
# STAT:      10     PlayerShip.Unknown57 = 28 (0x1c)
# STAT:     256     PlayerShip.Unknown57 = 1073741828 (0x40000004)
# STAT:     572     PlayerShip.Unknown57 = 1073741830 (0x40000006)
# STAT:   41448     PlayerShip.Unknown57 = 4294967295 (0xffffffff)
```
~~We already have SingleScan (bit 4.1), DoubleScan (bit 4.2), ShowOnMaps (bit 4.3) which means LRS/Sci/Cap/etc. You think there's yet another visibility... for what, the 3D visibility?~~ I sit corrected - those were NPC not PlayerShip

**Comment by StarryWisdom** [comment]
note - this is for object player ship not npc - we have no scan fields for them

**Comment by NoseyNick** [comment]
Corrected above - DOH!
PlayerShip.Unknown57 still looks plausible though yup.

**Comment by NoseyNick** [comment]
PlayerShip.Unknown57 - I have notes "for Player's ship to show on Sci/CapMap?"

**Comment by StarryWisdom** [comment]
I seem to have opened this twice - #163 is the same issue after I confirmed so closing this one
