### ISSUE TITLE
extra padding byte for engineering console

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#159]
Engineering Console has a 1 byte value not set by a bit field - I think that may just be from before we understood 24 bits = 4 byte field.

**Comment by rjwut** [comment]
I don't see the problem you're referring to, here. The docs say that the bit field is 4 bytes, not 3, and does not mention an unknown byte after the bit field.

**Comment by StarryWisdom** [comment]
um and I've double checked and its gone ... maybe I didnt refresh my browser properly :/ ?
