### ISSUE TITLE
packet 0x4c821d3c subtype 0x05 and 0x06

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#16]
I have seen 18 instances in 2 games of undocumented packet 0x4c821d3c subtype 0x05, payload 4 bytes, all zeroes, No idea if that's a 0 int, float, boolean, or enumerated something. :-(
Also half a dozen packet 0x4c821d3c subtype 0x06, payload 4 bytes all zeroes too. :-(
Every example I have seen was sent from Helm Client to Server. Will try to recreate, unless anyone has better details?
[moving to an issue of its own]

**Comment by NoseyNick** [comment]
0000000 ef be ad de 20 00 00 00 02 00 00 00 00 00 00 00
0000020 0c 00 00 00 3c 1d 82 4c 05 00 00 00 00 00 00 00

0000000 ef be ad de 20 00 00 00 02 00 00 00 00 00 00 00
0000020 0c 00 00 00 3c 1d 82 4c 05 00 00 00 00 00 00 00

**Comment by chrivers** [comment]
I'll include this information in my next update about unknown packets. Let me know if you have any more information about them :)
