### ISSUE TITLE
consistency between pc2.3(Hull ID) & npc1.7(Vessel type)

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#165]
both of these fields refer to the same thing - logically they should have the same name (another logical name is uniqueID - taken from vessel data)

imo any name just one thats consistent would be nice

**Comment by NoseyNick** [comment]
Mission scripts call it...
```xml
<create type ="enemy" hullID="4001" />
```
vesselData.xml calls it...
```xml
<vessel uniqueID="1000" />
```
To add to the confusion, my `parser.pl` calls them `PlayerShip.ShipType` and `NPCShip.VesselType`   :disappointed: 
I'll switch to whatever we choose here... and cast one vote for hullID, as it's "official" and not as vague as "uniqueID"

**Comment by NoseyNick** [comment]
See also `Base.VesselType` (bit 1.5)

**Comment by NoseyNick** [comment]
Also `AllShipSettingsPacket` Ship type (int)

**Comment by NoseyNick** [comment]
Also `SetFighterSettingsPacket` Vessel type (int)
[yeah I think I'm done for now   :stuck_out_tongue_winking_eye: ]

**Comment by NoseyNick** [comment]
Anyone know of a good way to vote on GitHub?
I think my preference would be for hullID, from mission-file-docs.txt
The only other "semi-official" one would be uniqueID but that feels potentially confusing in protocol descriptions.
