### ISSUE TITLE
ClimbDivePacket Type: 0x4c821d3c:0x1b can contain Direction 5,6,8?

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#17]
I have seen a few (very few) ClimbDivePacket Type: 0x4c821d3c:0x1b but Direction (int) is 5, 6, or 8, NOT +1 / -1. Will try to recreate, unless anyone has better details?
[moving to an issue of its own]

**Comment by rjwut** [comment]
Could you include a dump of the captured packets?

**Comment by NoseyNick** [comment]
0000000 ef be ad de 20 00 00 00 02 00 00 00 00 00 00 00
0000020 0c 00 00 00 3c 1d 82 4c 1b 00 00 00 05 00 00 00

0000000 ef be ad de 20 00 00 00 02 00 00 00 00 00 00 00
0000020 0c 00 00 00 3c 1d 82 4c 1b 00 00 00 06 00 00 00

0000000 ef be ad de 20 00 00 00 02 00 00 00 00 00 00 00
0000020 0c 00 00 00 3c 1d 82 4c 1b 00 00 00 08 00 00 00

**Comment by NoseyNick** [comment]
OK, I'm wondering if Climb/Dive has moved to 0x4c821d3c:0x1c (payload 1 float, usually +/-1) and 0x4c821d3c:0x1b is now some other command, payload one int, values 5/6/8 seen?

**Comment by chrivers** [comment]
@noseynick do you remember which version this was for?

**Comment by chrivers** [comment]
It turns out, quite a few client packets got shuffled around between 2.1.1 and 2.4.0 (maybe at 2.3.0)

Check out the different between ValueInt210 and ValueInt240 here:

https://github.com/chrivers/isolinear-chips/blob/master/protocol/parser.stf

I think this explains most of the confusion

**Comment by dthaler** [comment]
With the latest comment, this issue should be able to be closed now.
