### ISSUE TITLE
jam32/jamCRC and crc32

### ISSUE THREAD

**Issue by StarryWisdom** [artemis-nerds/protocol-docs#178]
I think it would be helpful to mention that the jamCRC hash is a bitwise not of the CRC32 hash
To this non java programmer knowing that is more helpful than the sample code .... which link to a dead link anyway
Unsure if it should be noted under ButtonClickPacket or Packet Structure

I guess a first draft of changes - under Packet Structure change
"This value is a JamCRC hash of the internal name of the packet type."
to something like
"This value is a bitwise not of a CRC32 hash (aka JamCRC) of the internal name of the packet type."
or 
"This value is a JamCRC hash of the internal name of the packet type. JamCRC is a bitwise not of a CRC32 hash"

under ButtonClickPacket
either update and move the sample code link to the Packet Structure part of the doc and update the text "This is a hash of the button's label computed using the JamCRC hash algorithm." to either match as above or refer to above like "This is a hash of the button's label computed using the JamCRC hash algorithm. See Packet Structure for details on JamCRC"

**Comment by NoseyNick** [comment]
Resolved by #183 ?
