### ISSUE TITLE
PlayerShipUpgradePacket details

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#18]
[moving to its own issue]

Player Ship Upgrades object appears to be...
Bit field (11 bytes)
UpgradeInUse (bits 1.1-4.4 = 28 byte array)
UpgradeQuantity? (bits 4.5-7.8 = 28 byte array)
... perhaps in the order that you've already hacked at, EG bit 5.3=LateralArray?
UpgradeCountdown (bits 8.1-11.4 = 28 short array)

I quite frequently see sequences like:
ObjUpgrades(id=1025, .... LateralArray5_3=3 ...)
ObjUpgrades(id=1025,Unknown1_7=1,Unknown8_7=299)
... Unknown8_7 counts down 299 .. 0
ObjUpgrades(1025,Unknown1_7=0,LateralArray5_3=2),

Or a similar sequence with...
...CetrociteCrystal5_1=1...
Unknown16=1,Unknown8_6=299
Unknown8_6=298 ... and down to...
Unknown86=0
Unknown16=0,CetrociteCrystal5_1=>0

Same pattern with Unknown21 vs SecretCodeCase5_5 vs Unknown91
We have 28 bytes for upgrades "in use", 28 bytes for upgrade "quantities", 28 shorts for upgrade countdowns whilst in use, total 84 bits of the 11-byte bitfield.

Running "strings Artemis.exe" and looking for "likely" strings, I believe the complete list of upgrades, in order, is:

| ID | Name | Class | Notes |
| --- | --- | --- | --- |
| 00 | Infusion P-Coils | Engine Boost | 5 Minute 10% Impulse and Warp Speed Boost |
| 01 | Hydrogen Ram | Maneuver Boost | 5 Minute 10% Turn Speed Boost |
| 02 | Tauron Focusers | Weapons Boost | 5 Minute 10% Beam and Reload Speed Boost |
| 03 | Carpaction Coils | Shield Boost | 5 Minute 10% Shield Recharge Boost |
| 04 | Polyphasic Capacitors | Energy Boost | 5 Minute 10% Energy Recharge Boost |
| 05 | Coolant Reserves | Heat Reduction | 5 Minute 10% Faster Heat Reduction (AKA Cetrocite crystals?) |
| 06 | Lateral Array | Scanner Boost | 5 Minute Instant Target Scan |
| 07 | ECM Starpulse | Jammer Boost | 5 Minute Enemy Cannot Lock |
| 08 | Double Agent | Auto-Surrender | Can force one ship to auto surrender (AKA Secret Code Case?) |
| 09 | Wartime Production | Prod Boost | 10% (min +1) boost to all starting base munitions |
| 10 | Infusion P-Coils PERM | Engine Refit | Permanent 10% Impulse and Warp Speed Boost |
| 11 | Protonic Verniers | Maneuver Refit | Permanent 10% Turn Speed Boost |
| 12 | Tauron Focusers PERM | Weapons Refit | Permanent 10% Reload and Beam Speed |
| 13 | Regenerative Pau-Grids | Shield Refit | Permanent 10% Shield Recharge Speed |
| 14 | Veteran DamCon Teams | Faster DamCon | Damcon teams move/repair 10% faster |
| 15 | Cetrocite Heatsinks | Heatsink Refit | Heat builds 10% slower |
| 16 | Tachyon Scanners | Scanner Refit | Permanent 10% Scan Speed Boost |
| 17 | Gridscan Overload | Sensor Refit | Permanent 10% Range Booster |
| 18 | Override Authorization | Improved Prod | All bases produce 10% faster |
| 19 | Resupply Imperatives | Mission Enhance | 10% More missions |
| 20 | Patrol Group | Allied Combat | Additional TSN Escort Ship in-sector |
| 21 | Fast Supply | Allied Supply | Additional TSN Cargo Ship in-sector |
| 22 | Vanguard Refit | Improved Console | Perm 10% Boost to Impulse, Warp, and Turn Speed |
| 23 | Vanguard Refit | Improved Console | Perm 10% Boost to Beam, Shield and Reload Speeds |
| 24 | Vanguard Refit | Improved Console | Perm 10% Boost to Scan speed and Sensor Range |
| 25 | Vanguard Refit | Improved Console | Perm 10% Boost to Station production |
| 26 | Vanguard Refit | Improved Console | Perm 10% Boost to all Engineering Systems |
| 27 | Vanguard Refit | Systems Overhaul | Permanent 10% Boost to all Ship Systems |

**Comment by NoseyNick** [comment]
This order matches the "Upgrades" screen seen in-game too, although some of the above Notes don't become obvious unless / until you have picked them up (if ever)

**Comment by chrivers** [comment]
This is closed by #58 :)
