### ISSUE TITLE
ToggleShieldsPacket link points to ToggleRedAlertPacket

### ISSUE THREAD

**Issue by aiden-w-135752345** [artemis-nerds/protocol-docs#181]
In the packet types table, clicking the link saying ToggleShieldsPacket shows the ToggleRedAlertPacket packet structure. Also, the section for ToggleShieldsPacket has the id for ToggleRedAlertPacket:
`<section id="toggleredalertpacket">`

**Comment by NoseyNick** [comment]
Thanks Aiden, easy fix in PR #182 will hopefully be reviewed / approved / merged soon.

**Comment by NoseyNick** [comment]
Will be fixed by #188 , which is more comprehensive than #182 - now dropped.
