### ISSUE TITLE
Packet 0x0351a5ac subtype 0x06 (Game Master?)

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#19]
I have seen a grand total of THREE packets 0x0351a5ac:0x06, client to server, I think from a Game Master
Payload seems to contain 3 floats which LOOK like they might be x/y/z coords?

0000000 ef be ad de 28 00 00 00 02 00 00 00 00 00 00 00
0000020 14 00 00 00 ac a5 51 03 06 00 00 00 00 00 7a 47
0000040 00 00 00 00 55 b9 69 47

0000000 ef be ad de 28 00 00 00 02 00 00 00 00 00 00 00
0000020 14 00 00 00 ac a5 51 03 06 00 00 00 00 0c 78 47
0000040 00 00 00 00 ab 62 32 47

0000000 ef be ad de 28 00 00 00 02 00 00 00 00 00 00 00
0000020 14 00 00 00 ac a5 51 03 06 00 00 00 00 0c 78 47
0000040 00 00 00 00 ab 62 32 47

Might be Game Master clicking on empty bits of the map? Will try to recreate

**Comment by chrivers** [comment]
You're right, this is in fact the GM Select Location packet. The packet type is documented in master. I suggest closing this issue :)

**Comment by mrfishie** [comment]
This is indeed the [GameMasterSelectLocationPacket](https://artemis-nerds.github.io/protocol-docs/#gamemasterselectlocationpacket) and has already been documented.
