### ISSUE TITLE
Document composite data types

### ISSUE THREAD

**Issue by IvanSanchez** [artemis-nerds/protocol-docs#2]
Write docs about the composite data types used by Artemis (as implemented by `node-asbs-lib`):
- Static structs
- Bitmapped structs
- Static arrays
- Byte-bound arrays

**Comment by rjwut** [comment]
This sounds like a reasonable idea. Could you point me to some examples in `node-asbs-lib` so that I can try to be consistent with terminology?

**Comment by IvanSanchez** [comment]
Sure. Starting here https://github.com/artemis-nerds/node-asbs-lib/blob/master/src/data-types.js#L197 and up to line 420-ish.

Maybe structs are too trivial (just the generic name of a bunch of values next to each other, always in the same order, always the same size). Most object updates use our friend the bitmapped struct.

ByteBoundArrays are used by the DamConInfo and the GameOverStats packets. Static-sized arrays are just used by AllPlayerShipSettings.
