### ISSUE TITLE
HelmJumpPacket Type: 0x0351a5ac:0x04 [from client] is actually 0x05?

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#20]
0x0351a5ac:0x04 is listed in the doc as both "EngSetEnergyPacket" and "HelmJumpPacket".
HelmJumpPacket seems to actually be subtype 0x05 (like the table at the top of that section, in fact)

**Comment by rjwut** [comment]
Fixed.
