### ISSUE TITLE
GameStartPacket Type: 0xf754c8fe:0x00 [from server] is back, but not GameStartPacket?

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#21]
Doc says:

> GameStartPacket
> Type: 0xf754c8fe:0x00 [from server]
> Sent when the simulation starts. This packet appears to have been discontinued as of v2.1.1.

It's back in v2.2.0, but doesn't seem to be related to Game Start, it seems to be:
0xf754c8fe:0x00 Object type (int) Object ID (int)
... and frequently happens right before DestroyObjectPacket, EG this torpedo:

0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 00 00 00 00 0b 00 00 00
0000040 95 06 00 00 ef be ad de 1d 00 00 00 01 00 00 00
0000060 00 00 00 00 09 00 00 00 30 3e 5a cc 0b 95 06 00
0000100 00

Or this drone:
0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 00 00 00 00 10 00 00 00
0000040 98 06 00 00 ef be ad de 1d 00 00 00 01 00 00 00
0000060 00 00 00 00 09 00 00 00 30 3e 5a cc 10 98 06 00
0000100 00

Or this more complicated set of NPC Ships:
0000000 ef be ad de 24 00 00 00 01 00 00 00 00 00 00 00
0000020 10 00 00 00 fe c8 54 f7 00 00 00 00 05 00 00 00
0000040 78 06 00 00 ef be ad de 24 00 00 00 01 00 00 00
0000060 00 00 00 00 10 00 00 00 fe c8 54 f7 00 00 00 00
0000100 05 00 00 00 7a 06 00 00 ef be ad de 1d 00 00 00
0000120 01 00 00 00 00 00 00 00 09 00 00 00 30 3e 5a cc
0000140 05 78 06 00 00 ef be ad de 1d 00 00 00 01 00 00
0000160 00 00 00 00 00 09 00 00 00 30 3e 5a cc 05 7a 06
0000200 00 00

For lack of any more detail, I'm going to call it PreDestroyPacket for the moment. It might be something like "remove from map" before we destroy it? <shrug />

**Comment by rjwut** [comment]
I hesitate to name the thing when we don't know exactly what the packet does. Also, I'm noticing that the examples you're sending include more than one packet in each sample. (Note the presence of `ef be ad de` in the middle of the packet.)

**Comment by NoseyNick** [comment]
Indeed, I was demonstrating "frequently happens right before DestroyObjectPacket"

**Comment by dthaler** [comment]
This issue was fixed 8/25/16 in commit 76521f3f, so this issue should be closed now.
The protocol docs currently call this DestroyObjectPacket2.
