### ISSUE TITLE
Ship number is zero-based on v2.3

### ISSUE THREAD

**Issue by dthaler** [artemis-nerds/protocol-docs#28]
http://artemis-nerds.github.io/protocol-docs/#consolestatuspacket says
"Ship number (int)
    The number of the ship whose consoles are being described. This value is one-based, so by default the ship identified by 0x01 is named Artemis."

In Artemis v2.3, the value is zero-based, so by default the ship identified by 0x00 is named Artemis.

**Comment by rjwut** [comment]
Can we get a double-check on this? I just tested this recently against my 2.3.0 install and it still seems to be one-based.

**Comment by dthaler** [comment]
From all my observations with v2.3, ConsoleStatusPacket has 0 for Artemis, 1 for Intrepid, etc.
In the ObjectUpdatePacket, the player ship object's "Ship number" field seems to always be 1 now for all ships (i.e., it's no longer a ship number) from my observations.

**Comment by NoseyNick** [comment]
Does this mean there is technically no way to tell which PlayerShipObject is which? Or is it implied in the order?

**Comment by dthaler** [comment]
That's the issue I'm struggling with right now.  A close workaround is to use the Ship name, and correlate it with what was in the AllShipSettingsPacket.   There's two problems with that though.
1) If the client reconnects in the middle of a simulation, the ObjectUpdatePacket won't have the ship name in it.
2) If someone goes back to the console selection screen after the simulation is started, the ship can be renamed there and AllShipSettingsPacket will have the new name but ObjectUpdatePackets will still have the old name.

**Comment by dthaler** [comment]
Ah ha, figured it out.  In the ship object, bit 5.8 is for a byte that contains the ship index (0-7).
Also bit 6.1 is for an int that contains the Object ID of the fighter's capital ship, if the ship object is a fighter.

**Comment by rjwut** [comment]
Okay. I'm a little busy this week but I'll see if I can scrape together some time to update docs. Might not happen until next week.

**Comment by JordanLongstaff** [comment]
So if bit 5.8 is the actual ship index, then what is bit 2.2 supposed to be? This is what we previously thought to be the ship number, but now it's always 1.

**Comment by JordanLongstaff** [comment]
Hold on, now I'm testing with version 2.6.0 and I'm getting a value of 46 in bit 5.8.

**Comment by dthaler** [comment]
-1 (i.e., 0xFF) is a Fighter.  0-7 are capital ships.   I've observed other values (e.g., 0xCC) which appear to be uninitialized memory.  For example, I think I've seen that with a launched fighter whose client has dropped.   Maybe that's what you're seeing with 46, not sure.

**Comment by JordanLongstaff** [comment]
Actually, I figured out what happened. Bit 5.6 was previously read as 5 bytes, when it should've been read as one byte.

**Comment by dthaler** [comment]
As far as I know Robert's commit 2373d16b57d55a61e55a8085bfe1e015161ea4c8 on 2/14/2016 is correct.  Since I filed this issue, I am closing it.
