### ISSUE TITLE
SciScanPacket is listed twice under PacketTypes

### ISSUE THREAD

**Issue by dthaler** [artemis-nerds/protocol-docs#29]
http://artemis-nerds.github.io/protocol-docs/#packet-types says
"SciScanPacket  client  0x4c821d3c  0x13
SciSelectPacket     client  0x4c821d3c  0x10
SciScanPacket   client  0x4c821d3c  0x13"

The second occurrence of SciScanPacket should be removed.

**Comment by mrfishie** [comment]
Fixed! Thanks.
