### ISSUE TITLE
Include documentation for other Artemis data

### ISSUE THREAD

**Issue by mrfishie** [artemis-nerds/protocol-docs#3]
I think that it would be beneficial to broaden the topic of the docs to cover other data sources such as `vesselData.xml` and `.snt` files, rather than just the protocol. I've already done some work on this which I can commit when I have time if we want to do this.

Additionally, I think a standardized property nameset (e.g. names of entities, properties, and property behaviour, as well as how packets/packet properties match to entities and entity properties) is required that works across all of these formats, which can be used by all Artemis libraries, guaranteeing compatability. This would also aid documenting these libraries, as the majority of documentation concering game-related I/O would already be available.

**Comment by rjwut** [comment]
I like this idea and was thinking that it would be a good thing to have. Given that this project is named `protocol-docs`, it might make sense to make a separate project for it; maybe `file-format-docs`. Dunno, will think about it some more.

**Comment by rjwut** [comment]
[Forum post about .snt file format](http://artemis.forumchitchat.com/post/editing-snt-files-6751214)

**Comment by rjwut** [comment]
[ArtClientLib code for parsing vesselData.xml](https://github.com/rjwut/ArtClientLib/tree/master/src/net/dhleong/acl/vesseldata) (I have some updates for a couple of missing elements I haven't committed yet but will soon.)

**Comment by mrfishie** [comment]
I did [some work documenting vessel data](https://gist.github.com/mrfishie/deb0d87587fc71c0591f) a while ago when I was working on a draft documentation that I never finished.. It's pretty messy (and for some reason Gist keeps ignoring my attempts to make it render as markdown) but it might be able to be integrated in somehow.

Perhaps we could rename this repo to something more like `artemis-docs`, and then include all of the different sections?

**Comment by IvanSanchez** [comment]
By the way, [Glitter code](https://github.com/IvanSanchez/artemis-glitter/blob/master/vesselData.js) for parsing vesselData.xml and .snt files.

**Comment by rjwut** [comment]
I'm thinking that I'll just go ahead and document the other stuff under the existing repo without renaming it, at least for now. File formats are still a protocol. A few wording changes in the documentation itself should be sufficient.

**Comment by mrfishie** [comment]
Another thing I would like to see in these docs is entity behaviour. Not necessarily AI (this would probably be reverse-engineering 'too far' anyway), but more low-level details like how the impulse works (how does the impulse amount translate into acceleration, and how does this translate into velocity? how are the numbers in vessel data translated into the numbers used for this?)

**Comment by rjwut** [comment]
I've documented `vesselData.xml` and `*.snt` files, which were the major thrust of this issue, so I'm going to close it. There were a couple of minor things mentioned in the comments that people had suggested documenting; if we still want those, let's make separate issues for them.
