### ISSUE TITLE
Fighter launch packets in v2.3

### ISSUE THREAD

**Issue by dthaler** [artemis-nerds/protocol-docs#31]
**FighterLaunchPacket**
    TYPE: 0x4c821d3c : 0x1d [FROM CLIENT]
Notifies the server that a fighter is being launched.   In response, the server will send a FighterLaunchedPacket.
Payload
Subtype (int)
    Always 0x1d.
Object ID (int)
    The fighter's object ID that appeared in a FighterBayStatusPacket.

**FighterLaunchedPacket**
    TYPE: 0xf754c8fe : 0x17 [FROM SERVER]
Notifies the client that a fighter was just launched.
Payload
Subtype (int)
    Always 0x17.
Object ID (int)
    The fighter's object ID that appeared in a FighterBayStatusPacket.

**Comment by dthaler** [comment]
Also confirmed that the object ID in these packets and in the FighterBayStatus packet is a regular object ID.  That is, fighters appear as player ships in an ObjectUpdatePacket with subtype 1 (Player ship) with the object ID in these packets.

**Comment by rjwut** [comment]
Have we observed another packet when a fighter returns to the mothership?

**Comment by dthaler** [comment]
It would be good to add the fighter launch and fighter dock sequences to the Game Events section (http://artemis-nerds.github.io/protocol-docs/#game-events).

The fighter launch sequence is:
1. Client sends FighterLaunchPacket (0x4c821d3c : 0x1d)
2. Server sends FighterLaunchedPacket (0xf754c8fe : 0x17)
3. Server sends FighterBayStatusPacket (0x9ad1f23b) since the fighter is no longer there
4. Server sends ObjectUpdatePacket that includes the capital ship and its launched fighter(s) as separate ship objects

The fighter dock sequence is:
1. Fighter client sends HelmRequestDockPacket
2. Server sends DestroyObjectPacket to destroy the fighter's player ship object
3. Server sends FighterBayStatusPacket (0x9ad1f23b) since the fighter is now there
4. Server sends ObjectUpdatePacket that includes the capital ship and its launched fighter(s) as separate ship objects, but which no longer includes the now-docked fighter

**Comment by chrivers** [comment]
This seems to be documented in the newest docs. Is there anything missing, or should we close this issue?

**Comment by mrfishie** [comment]
@chrivers We haven't added the Game Events sequences that @dthaler proposed just above, which I suppose is why this isn't closed. I'll whip up a quick pull request and then close this.

**Comment by chrivers** [comment]
Ah, I did miss something. That sounds great! :)
