### ISSUE TITLE
EngPlayerUpdatePacket and WeapPlayerUpdatePacket need array discussion

### ISSUE THREAD

**Issue by dthaler** [artemis-nerds/protocol-docs#4]
MainPlayerUpdatePacket says:
"The payload consists of an array of ship entries. Parsing continues in a loop until the end of the packet is reached, or the object type byte is 0x00."

The same is true for EngPlayerUpdatePacket and WeapPlayerUpdatePacket.

**Comment by IvanSanchez** [comment]
I think this is the same issue that I wrote about in https://github.com/artemis-nerds/protocol-docs/commit/b72ef1a8e6e8785a41f4703bb3a682c6ddd1e82e#diff-eacf331f0ffc35d4b482f1d15a887d3bR948 and that @rjwut referred to in the forums: 

> you're saying not only that a single packet can contain multiple object updates, but that it can contain updates for multiple types of objects (e.g., a single packet might contain 4 nebulae, 20 asteroids and a space monster) ?

@dthaler Have you been able to capture a packet which includes a MainPlayerUpdate, EngPlayerUpdate and WeapPlayerUpdate chained together?

If that's the case, we can just delete the "Parsing continues in a loop" bit from the MainPlayerUpdate packet.

**Comment by dthaler** [comment]
No, each contains an array of elements of the same subtype.  I've never seen different subtypes chained together in the same packet.  The MainPlayerUpdatePacket page is correct.  The other two need the same statement added.

**Comment by rjwut** [comment]
@dthaler You're saying that EngPlayerUpdatePacket and WeapPlayerUpdatePacket can contain updates for multiple player ships? I haven't done much multi-bridge packet capturing, so I've never been able to observe this.

**Comment by IvanSanchez** [comment]
@rjwut Remember that it's easy to do multi-bridge capturing with https://github.com/artemis-nerds/node-asbs-dummy-ai - if you need some specific functionality (e.g. an engineering console per ship) I can make modifications.

**Comment by dthaler** [comment]
@rjwut: "You're saying that EngPlayerUpdatePacket and WeapPlayerUpdatePacket can contain updates for multiple player ships?"   Yes, exactly.  I had to deal with this when adding new DMX cues to Artemis DMX Tools, which rely on those packets.  Since I use C++, I wrote my own protocol parser based on these docs which were very helpful.
