### ISSUE TITLE
Document should include every known packet type, even those without known purpose

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#45]
I propose that we list every observed packet type in the protocol docs, with as much information as we have.

At the same time, these subtypes should be clearly labeled as being wholly or partially unknown.

Packets with completely unknown function, will be prefixed with "_UNKNOWN" or similar prefix, to clearly distinguish them from the known packets.

Will you accept a PR for this?

**Comment by mrfishie** [comment]
As far as I know, we do list and document packets that we don't know much about (with many of their fields marked as 'Unknown'), and other packets whose purposes are completely unknown are in a table before the main listing.

PRs for anything that helps to improve the documentation are always welcome, so feel free to submit one with your proposal :)

**Comment by chrivers** [comment]
Okay, I will do that :)

From personal experience, as well as looking at the issues list, there are at least a small handful of packet types and subtypes that aren't mentioned in the main document. My plan is to merge the "unknown packets" table with the normal packets table, and write a real section for each of them, even if we are unclear on most (or all) of the info on them.

Because at the very least, we know they exist, we know their IDs, and we have a few samples of the data.

**Comment by mrfishie** [comment]
> there are at least a small handful of packet types and subtypes that aren't mentioned in the main document.

That's a very good point - I hadn't realised how many observed packets we had that hadn't been listed in the documentation. While adding the ones we've missed would be great to solve the immediate problem, I think we also need to think about how to keep the documentation up-to-date with packet info reported here in the future to make sure the documentation contains everything we know about everything all the time.

**Comment by rjwut** [comment]
I agree that it would be good for the [table of packet types](https://artemis-nerds.github.io/protocol-docs/#packet-types) to be in numerical order by packet type then subtype, while the document itself (and the corresponding floating table of contents at the left) remains in alphabetical order. That would make it easy to locate any one packet by name, but would still provide the advantages previously mentioned for listing them in numerical order.

The table is built dynamically on page load. It is currently done in a single pass; the table is written as the packet `<section>`s are iterated. This would have to change to a two-pass mechanism: one pass to collect them into an array, which is then sorted, then a second pass to write the table.

**Comment by rjwut** [comment]
I agree that unknown packet types should be folded into that table, and `<section>`s created for them.

**Comment by chrivers** [comment]
@mrfishie Do you have any suggestions for how to create more correct documentation?

I've experimented with auto-generating parsers and headers from the documentation, but ultimately the format was so loosely structured, that I had to just perform the bulk conversion step, and maintain it by hand.

And now I'm exactly faced with a similar problem - I have to constantly keep track of the commit log, to match fixes to the document with fixes to my program.

For me, the optimal solution would be to convert the current quite-reasonably structured document into an actual parsable data structure. This data structure could then quite simply be auto-generated into Rust structures, Java classes, JS parsers, etc, as well as the bulk of the body document.

A simple python script could do almost all of the heavy lifting - I know this, because I have already tried it. The absolutely painful part, was trying to extract rigidly structured data, from a semi-structured document. You don't truly realize how many minor inconsistencies and style changes there are, until you try to write a parser for it ;-)

This is absolutely a topic for somewhere else, but personally the idea of a structured source is extremely appealing to me. It would not be a lot of work to generate the current document from this, once converted, and it would then give us a building block to generate other things from (over time).

Who is on board with this? In any case, we should take the discussion somewhere else, although I'm not quite sure where... where do you guys communicate? :)

**Comment by rjwut** [comment]
@chrivers I like the idea. Here is as good a place to discuss it as anywhere else, actually. The only other place I would think of is the Artemis forums, but I think GitHub's a more appropriate place for it.

**Comment by chrivers** [comment]
@rjwut Sounds good, I'll make a new issue for it.

**Comment by mrfishie** [comment]
@chrivers Have you created an issue for this?

In the past I have experimented with converting the packet documentation in to some kind of structured file which would allow us to generate the documentation as well as packet parsers as you've explained.

I'm definitely on board with this idea. I'll try to find the attempt I was previously working on which might give us a platform to start, too.

**Comment by chrivers** [comment]
I have now, it's issue #50. I have a recent python script that can parse most of the current HTML, including types and descriptions. It doesn't need to be perfect, since we only have to do it once. I'll try to clean it up and post it, after I get some sleep.
