### ISSUE TITLE
Packet type list should be sorted by packet type, not alphabetically

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#46]
When implementing or debugging the protocol, it's much more useful to be able to look up packet types by the supertype and subtype, rather than the name (which can even change in the future).

It makes perfect sense for the packet description list to be alphabetically sorted, but I think the index should be numerical - or, a second index should be included, which is numerically sorted. Since it's js-generated to begin with, this should be trivial to implement.

Will you accept a PR for this?

P.S: Can I join your group? ;-) I can't apply for membership, that function seems to be disabled.

**Comment by mrfishie** [comment]
> I think the index should be numerical - or, a second index should be included, which is numerically sorted.
Another option could be a live search feature that searches both packet names, types and subtypes. 

> Can I join your group?
I'm totally OK with that, but I'll leave the decision up to @rjwut as he's the most active person in the group right now.

**Comment by mrfishie** [comment]
> I think the index should be numerical - or, a second index should be included, which is numerically sorted.

Another option could be a live search feature that searches both packet names, types and subtypes.

> Can I join your group?

I'm totally OK with that, but I'll leave the decision up to @rjwut as he's the most active person in the group right now.

**Comment by chrivers** [comment]
I like the live search feature, but it's also a bit harder to implement. Frankly, I'm not sure I have time for it right now - I just use ctrl+f whenever I need to search for something.

The reason I want to change the index, is because it shows interesting patterns in our knowledge of the packet types. For example, there was a quite clear hole in the list here:

  0xf754c8fe -> (0x07, 0x08)

And it turns out, looking at the issue list, that these packet subtypes have indeed been observed. So it stands to reason that the subtypes are probably fully (or close to fully) populated, which would indicate we might also see {0x01, 0x02, 0x0e, 0x13, 0x16) as subtypes for 0xf754c8fe. In fact, I think I might have caught a few samples of some of these.

**Comment by mrfishie** [comment]
Ah, I see your reasoning, and I agree that it would definitely be useful. For ranges of subtypes where we don't have any packets observed, perhaps we could also have an entry in the packet list highlighted somehow? (and with the text 'Unknown', perhaps)
This shouldn't be too hard to add, and I'd be willing to do it if you want to submit a PR for re-ordering the list.

**Comment by rjwut** [comment]
I agree that it would be good for the [table of packet types](https://artemis-nerds.github.io/protocol-docs/#packet-types) to be in numerical order by packet type then subtype, while the document itself (and the corresponding floating table of contents at the left) remains in alphabetical order. That would make it easy to locate any one packet by name, but would still provide the advantages previously mentioned for listing them in numerical order.

The table is built dynamically on page load. It is currently done in a single pass; the table is written as the packet `<section>`s are iterated. This would have to change to a two-pass mechanism: one pass to collect them into an array, which is then sorted, then a second pass to write the table.
