### ISSUE TITLE
Add long/int64 type

### ISSUE THREAD

**Issue by mrfishie** [artemis-nerds/protocol-docs#5]
As pointed out in https://github.com/artemis-nerds/node-asbs-lib/pull/15, the [generic mesh packet](https://artemis-nerds.github.io/protocol-docs/#genericmeshpacket) specifies a 'long' type for bit 1.6, but this type isn't in [the data types](https://artemis-nerds.github.io/protocol-docs/#data-types) in the documentation.

Seeing as property is an unknown in the generic mesh packet, and is the only instance of 'long' anywhere in the docs, could it be a mistake? Should we add it as a type?

I have created a pull request with the (simple) change if we decide we want it: https://github.com/artemis-nerds/protocol-docs/pull/6

**Comment by mrfishie** [comment]
Actually, should the 'long' in the generic mesh packet be an 'int'?

**Comment by rjwut** [comment]
My feeling is that there are no values in the Artemis universe that would require a long to store them, so I think it's very unlikely that the fields in question are actually longs. If it truly is 8 bytes, it might be two ints or floats controlled by the same bit flag, for example. I think that until we can confirm that the long type is actually used, there's no point in supporting it.
