### ISSUE TITLE
__client_unknown__0x4c821d3c_0x17 is actually SetShipSettings for v2.4.0+

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#53]
So, it turns out subtype 0x17 is actually like SetShipSettings, but for versions greater than 2.1.1. I have confirmed that it's valid for 2.4.0:

```
[*] Read client frame: Client::SetShipSettings_v240 { ship: Ship { drive_type: Warp, ship_type: 12, accent_color: 0, _unknown_1: 1, name: "Artemis\u{0}" } } (0 bytes)
[*] Read client frame: Client::SetShipSettings_v240 { ship: Ship { drive_type: Warp, ship_type: 11, accent_color: 0, _unknown_1: 1, name: "Artemis\u{0}" } } (0 bytes)
[*] Read client frame: Client::SetShipSettings_v240 { ship: Ship { drive_type: Warp, ship_type: 10, accent_color: 0, _unknown_1: 1, name: "Artemis\u{0}" } } (0 bytes)
[*] Read client frame: Client::SetShipSettings_v240 { ship: Ship { drive_type: Warp, ship_type: 9, accent_color: 0, _unknown_1: 1, name: "Artemis\u{0}" } } (0 bytes)
[*] Read client frame: Client::SetShipSettings_v240 { ship: Ship { drive_type: Warp, ship_type: 8, accent_color: 0, _unknown_1: 1, name: "Artemis\u{0}" } } (0 bytes)
[*] Read client frame: Client::SetShipSettings_v240 { ship: Ship { drive_type: Warp, ship_type: 7, accent_color: 0, _unknown_1: 1, name: "Artemis\u{0}" } } (0 bytes)
[*] Read client frame: Client::SetShipSettings_v240 { ship: Ship { drive_type: Warp, ship_type: 6, accent_color: 0, _unknown_1: 1, name: "Artemis\u{0}" } } (0 bytes)
```

This happens when the helm player presses "Configure ship" while in the station selector.

However, issue #14 has some (confirmed) sightings of this packet with just 0x00000000 as the payload.

I don't have a good explanation for the weird special case, but this explains all non-zero sightings of this packet.

**Comment by rjwut** [comment]
Does the original SetShipSettings still get sent? I think it does, but I'd need to check.

**Comment by chrivers** [comment]
I just checked my historic logs. I have plenty of 0x17, but not a single 0x16 from 2.4. I have 0x16 from 2.1.1, so my guess would be that the change happened somewhere between those versions.

**Comment by chrivers** [comment]
There's something else interesting about 0x16 and 0x17. The data they send is exactly equal to 1/8th (one element) of the AllShipSettings. Or in other words, AllShipSettings is an array of 8 "Ship" structs. This is interesting, because it's the first non-trivial example I have seen, of structs shared between client and server packets. I think we should document it separately. But maybe we should reach good consensus on #50 first :)

**Comment by dthaler** [comment]
With the latest comment, this issue should be able to be closed now.
