### ISSUE TITLE
Missing special ability: ELITE_ANTI_SHIELD

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#55]
From the docs:

```
  const int ELITE_ANTI_SHIELD          = 1024
```

**Comment by chrivers** [comment]
Sorry, I misread.. ignore

**Comment by chrivers** [comment]
To add to the confusion, I didn't misread. I misquoted :)

There really is a missing elite ability:

```
  const int ELITE_SHIELD_STEAL = 0x800
```

We should consider if the "canonical"(?) names from mission-file-docs should be used instead of the current elite ability bits.

**Comment by rjwut** [comment]
Definitely we should make clear the correlation between the canonical names used in mission scripting and these enumeration values. Also, vesselData.xml no longer uses the term "elite" to refer to ships with these abilities; they are now consistently referred to as "special abilities" across the board, so our documentation should eliminate all references to the word "elite."

**Comment by chrivers** [comment]
I feel this is adressed by #60. Feel free to close this issue, unless I missed something.
