### ISSUE TITLE
Easy statistical analysis

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#62]
Guys, I need your help for an idea. Right now, we don't have a test suite for the protocol, nor do we have a complete and full understanding of every field. In fact, I suspect a small number of the rarely used field descriptions to be wrong in the current docs.

I've figured out a good way to solve several of these problems at once. If we had some raw data logs (I have some for my own use already), then first of all, we could test that our programs could parse all this data as is. But more interestingly, we could make a program that describes the range of values for each field. So we could see the min/max values (ints and floats) observed values (strings) converted values (enums) and so on. This would most certainly tell us almost straight away if we have any parsing problems.. and it would make it much easier to test a hypothesis against an existing corpus.

I've already implemented this for a few specific cases. However, I could really use some help in collecting more bulk data.

What I would really like, if you have it available, is a text file with a hex dumped packet per line, without the framing (deadbeef prefix and header)

Thoughts? :)

**Comment by rjwut** [comment]
IAN has a test harness that can do this sort of thing. Check out the test directory for code.

**Comment by chrivers** [comment]
That looks good, but it seems to be mostly for testing correctness of known fields? That's great, but what I want to do is analyze a lot of test data, to verify and figure out some of the more uncertain, or completely unknown, fields :)

So if anyone has as many megabytes of packet dumps as they can upload, I'd like to see them. Otherwise I guess I'll have to just generate it myself :)

**Comment by mrfishie** [comment]
I don't believe I have any packet dumps that would be useful, but I was considering if doing some kind of semi-auto packet dump generation would be possible - a script could be used to generate mission files that would result in different behaviour, an Artemis client and server could be started, and packets between them could be stored (and then repeat with a different combination of things in the mission files). Naturally this wouldn't be able to provide info for things that are different between mission games and normal games, but would this be useful?

**Comment by NoseyNick** [comment]
I have been using a proxy that accepts connections on port 2010 and forwards all data to/from a real artemis server on port 2011, whilst simultaneously saving the entire streams to different files for later reassembly.
Another option is Wireshark, "follow TCP stream", and saving it.
Something a bit more intelligent that can DROP a lot of the well-known obvious stuff, and only capture "interesting" packets might be worthwhile?

**Comment by NoseyNick** [comment]
... so I could probably upload 630MB of COMPRESSED data, 2.2GB raw, so ~4GB HEX without DEADBEEF, depending on how much of the rest of the header you care for (Client/server "Origin" byte? Or honestly no header at all?)
... and if I got serious about capturing traffic at some of our club meetings, plenty more   :-)

**Comment by chrivers** [comment]
See, that's exactly what I'm looking for! :)

I also have that kind of proxy - works exactly the same, and just dumps the data (with deadbeef deframing) to line-based text files, with hex encoding of the data.

So I have all the tools I need to generate the data, but it's pretty invaluable to have a large corpus of data, especially from real-world situations. It's sometimes hard to simulate an actual space battle, when you're just a home pressing buttons :)

Having your data dumps would be great. My preferred format is without the deadbeef frames, but whatever you have works, honestly. I just care about volume, so I can collect a decent test corpus.

Perhaps you can send me an e-mail, and we can coordinate further? I'd be happy to send you the (little) data I have also.
