### ISSUE TITLE
New packet type 0x0351a5ac	:0x07

### ISSUE THREAD

**Issue by chrivers** [artemis-nerds/protocol-docs#63]
I let my proxy run for a while to gather data, and test the parsing. I discovered 0x0351a5ac    :0x07, which seems to be sent quite a lot in 2.4.0, in the right circumstances. Unfortunately, I wasn't looking at the game while this happened, so I don't know what the "right circumstances" are..

Below is a quoted sample of the attached file. They all seem to be the same length.

```
aca55103070000000000003fe903000000000000a50e43470000000088f342470000000000000000000000000000803f
aca55103070000000000003fe903000000000000640e4347000000004df442470000000000000000000000000000803f
aca55103070000000000003fe903000000000000280e434700000000fef442470000000000000000000000000000803f
aca55103070000000000003fe903000000000000e10d434700000000cef542470000000000000000000000000000803f
aca55103070000000000003fe9030000000000008c0d434700000000b6f642470000000000000000000000000000803f
aca55103070000000000003fe903000000000000090d43470000000036f842470000000000000000000000000000803f
aca55103070000000000003fe9030000000000009e0c4347000000006ff942470000000000000000000000000000803f
aca55103070000000000003fe903000000000000270c434700000000c8fa42470000000000000000000000000000803f
aca55103070000000000003fe903000000000000a50b43470000000042fc42470000000000000000000000000000803f
aca55103070000000000003fe903000000000000180b434700000000dcfd42470000000000000000000000000000803f
aca55103070000000000003fe9030000000000007f0a43470000000097ff42470000000000000000000000000000803f
aca55103070000000000003fe903000000000000db09434700000000740143470000000000000000000000000000803f
aca55103070000000000003fe9030000000000004a094347000000009a0343470000000000000000000000000000803f
aca55103070000000000003fe9030000000000008e08434700000000b90543470000000000000000000000000000803f
aca55103070000000000003fe903000000000000d007434700000000de0743470000000000000000000000000000803f
aca55103070000000000003fe9030000000000001107434700000000070a43470000000000000000000000000000803f
aca55103070000000000003fe9030000000000005206434700000000340c43470000000000000000000000000000803f
aca55103070000000000003fe9030000000000009b054347000000006f0e43470000000000000000000000000000803f
aca55103070000000000003fe903000000000000da04434700000000a61043470000000000000000000000000000803f
aca55103070000000000003fe9030000000000001a04434700000000e21243470000000000000000000000000000803f
aca55103070000000000003fe9030000000000005903434700000000231543470000000000000000000000000000803f
aca55103070000000000003fe903000000000000b202434700000000821743470000000000000000000000000000803f
aca55103070000000000003fe903000000000000f201434700000000cc1943470000000000000000000000000000803f
aca55103070000000000003fe90300000000000032014347000000001b1c43470000000000000000000000000000803f
```

**Comment by chrivers** [comment]
[0x0351a5ac_0x07.txt](https://github.com/artemis-nerds/protocol-docs/files/499531/0x0351a5ac_0x07.txt)

**Comment by rjwut** [comment]
I have guesses about some of the fields. I'll use the values from the first packet as an example. After the type and subtype ints:
- `0000003f` as a float is 0.5. Not sure what it means, but I think in context it might make sense.
- `e9030000` as an int is 1001. This may be an object ID.
- After the zeroes, you get `a50e4347`, `00000000`, and `88f34247`. These are almost certainly world coordinates; interpreting them as floats produces (49934.645, 0, 49907.531), which would be pretty close to the center of the game world, where _Artemis_ spawns.
- The last four bytes, `0000803f`, are 1.0 when interpreted as a float. Again, not sure what it means, but context may help.

**Comment by chrivers** [comment]
I was just on my way to bed, so I left out some details which might be interesting. Here's what I can say about the test session the dump is from:
- Definitely running stock 2.4.0 with no mods
- Running almost-vanilla or only very slightly modified "gm button test" map that Thom made, from the gm buttons discussion
- Was showing a friend the new gm buttons, so I created a few asteroids, some enemies, and teleported an enemy. Maybe clicked a few other buttons too
- Left the game for a while, and artemis got destroyed in the end, after having been shot at for a long, long time.
- I think there might have been an enemy carrier in the map

That's what I remember right now. Since the subtype 0x06 is about fighters (and is also quite new), one could speculate that this is related to fighters or drones.. perhaps?

One very strange thing, is that it falls under the "valueFloat" canonical name, but it's clearly not a single element, nor do they all look like floats. In a small map, 1001 sounds exactly like an object id - probably of the first enemy.

So that's a bit weird...

**Comment by chrivers** [comment]
Hello again :)

It's been a while since I've worked on Artemis, but I've had a chance to take it up again recently.

I've uncovered a good bit of new information, including a better desc of FighterUpdate:
```
    FighterUpdate
        # Same values as HelmSetSteering
        rudder: f32,

        fighter_id: u32,

        __unknown_1: f32,
        x: f32,
        y: f32,
        z: f32,

        __unknown_2: f32
        __unknown_3: f32
        __unknown_4: f32
        __unknown_5: f32
```

I maintain my protocol spec in STF format here:

https://github.com/chrivers/isolinear-chips/

Specifically, FighterUpdate is part of the Client Packet type:

https://github.com/chrivers/isolinear-chips/blob/master/protocol/client.stf
