### ISSUE TITLE
Accent color?

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#66]
Could use a better description of "Accent Color". Is it RGB? I think there is some sort of HSV thing going on here?

**Comment by NoseyNick** [comment]
Answering my own question, AccentColo[u]r parses a WHOLE lot better as a Float, not an Int. It has a value 0.0 (red) to 1.0 (the other red).
Multiply by 360 to match the description at https://en.wikipedia.org/wiki/Hue

**Comment by NoseyNick** [comment]
The default ships are all Warp, LightCruiser, the accent colours / names are:
   0, 'Artemis'
   0.125, 'Intrepid'
   0.25, 'Aegis'
   0.375, 'Horatio'
   0.5, 'Excalibur'
   0.625, 'Hera'
   0.75, 'Ceres'
   0.875, 'Diana'

**Comment by chrivers** [comment]
Brilliant! That makes so much more sense than what we have so far :)

I'll update the stf with the new info, thanks!

**Comment by NoseyNick** [comment]
May I propose we also rename it "hue" so we don't have to argue about the correct spelling of colour vs color?   :-D

**Comment by chrivers** [comment]
I'm totally on board with "hue" - it makes more sense. I'll certainly update it in Isolinear Chips, but I don't have push rights for protocol-docs, so I can't make that kind of decisions here :)

**Comment by mrfishie** [comment]
I've just made a pull request to change it to Hue and add a little description. It also has the default values @NoseyNick provided, and I put in little coloured boxes beside each ship to demonstrate what the colour would be.

**Comment by rjwut** [comment]
Merged. Question: does it really go to 1.1? I would have thought the max would be 1.0 (exclusive).

**Comment by mrfishie** [comment]
Oh, that's a mistake on my part. I'll commit a fix in a moment.

**Comment by mrfishie** [comment]
@rjwut Fixed in https://github.com/artemis-nerds/protocol-docs/commit/0d3acacabba2d2c3decd141c244acf40cb3f4002
I'll close this issue now.
