### ISSUE TITLE
Perspective Packet now only toggles.

### ISSUE THREAD

**Issue by UserMcUser** [artemis-nerds/protocol-docs#72]
The Perspective Packet (0xf754c8fe : 0x12) is now apparently always the same - I see this <ef be ad de 1c 00 00 00 01 00 00 00 00 00 00 00 08 00 00 00 fe c8 54 f7 12 00 00 00> every time I click the button.

The reason is that Artemis now just toggles the perspective between 1st and 3rd rather than explicitly setting it. Not sure when this changed, but definitely after 2.1.5.

**Comment by UserMcUser** [comment]
Looks like the change happened after 2.3.0 - I don't have the 2.4.0 binaries to test with but for sure in 2.5.1 it just toggles the perspective.

**Comment by chrivers** [comment]
I can confirm that 2.4.0 also just toggles
