### ISSUE TITLE
0x4c821d3c subtypes 0x1e, 0x21, 0x22 seen

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#78]
"valueInt" says #52 (all client2server):

0x4c821d3c subtype 0x1e seen in some 2.4.0 games (so not very new).

3c1d824c1e000000fa030000
3c1d824c1e0000003e040000

Payload looks like a single integer, probably signifies launching a fighter given that it's followed by a lot of 0x351a5ac 0x07 (FighterPilotPacket) with the same int appearing in their "Object ID"

0x4c821d3c subtype 0x21 seen, just once, in one 2.6.204 game:

3c1d824c210000000000000000000000

FAIRLY sure I was mucking about on the "customise ship" screen as a Helmsman, but not sure exactly what I clicked   :disappointed:

0x4c821d3c subtype 0x22 seen in two 2.6.204 games:

3c1d824c22000000393000000000 # payload
3c1d824c22000000393000000001 # payload ...
3c1d824c2200000039300000000a # payload
3c1d824c22000000393000000100 # payload
3c1d824c22000000393000000101 # payload
3c1d824c22000000393000000200 # payload
3c1d824c22000000393000000300 # payload
3c1d824c22000000393000000400 # payload

FAIRLY sure these are sent from Weapons console, probably to do with the BioSig tagging / power, not sure what the first int(?) corresponds to (decimal 12345? Curious!), but 00..04 is probably the Tag Frequency, 00..0a the power.

0x4c821d3c subtypes 0x1f, 0x20 hypothesized but not seen.

**Comment by NoseyNick** [comment]
0x4c821d3c 0x1f seen, client2server, from a fighter. A few of each of:
3c1d824c1f0000000404000003040000 # 2.6.204 payload
3c1d824c1f0000000404000071040000 # 2.6.204 payload
Type, subtype, 04040000 is the fighter's objectID, 03040000 or 71040000 look like other Ship IDs.
I also have yet to recreate on other versions apart from 2.6.204.

**Comment by NoseyNick** [comment]
0x4c821d3c subtype 0x21 found, and exhaustively explored, with the help of my 13yr-old son Aiden learning to reverse-engineer Artemis protocols - our newest artemis-nerd?  :smile:

* Integer packet type (0x4c821d3c) - officially "valueInt" as per #52 
* Integer packet subtype (0x21) - SingleSeatSelection, as used by Helm/Mainscreen to "Customize ship"
* Integer (0), always zero, purpose unknown. We thought it might be "capital ship number" but no, it's always zero 
* A list of 0 to N SingleSeat records, one per capital ship bay, each:
  * Integer Type <vessel uniqueID="Type"> as seen in vesselData.xml
  * Integer Bay (numbered from 0 to N-1 bays in each class of capital ship)
  * String Name (provided by player)
  * String hullRace ("TSN", "Ximni", "Pirate" etc as seen in vesselData.xml)
  * String broadType
* List terminated by (Type?) Integer = 0

Strings (of course) often contain trailing rubbish, EG:
SingleSeatSelect(0,
  SingleSeatRec(123, 0, UTF16('1'), UTF16('Ximni'."\0".'eeee'), UTF16('player singleseat shuttle'."\0".'eeeeeeeeeeeeeeeeeeeeeeee')),
  SingleSeatRec(122, 1, UTF16('2'), UTF16('Ximni'."\0".'eeee'), UTF16('player singleseat shuttle'."\0".'eeeeeeeeeeeeeeeeeeeeeeee')),
  SingleSeatRec(120, 2, UTF16('3'), UTF16('Ximni'."\0".'eeee'), UTF16('player singleseat fighter'."\0".'eeeeeeeeeeeeeeeeeeeeeeee'))
);

**Comment by NoseyNick** [comment]
Unfortunately we also bring bad news about the 0x4c821d3c "valueInt" series :disappointed:
The SUBTYPES seem to change between versions.
0x4c821d3c:0x18 "HelmToggleReversePacket" seems to have become "Reset all Eng coolant to defaults" (double spacebar) at some point (version TBC, contents TBC)
0x4c821d3c:0x19 "RequestEngGridUpdate" has become "HelmToggleReverse"
0x4c821d3c:0x1a "TogglePerspectivePacket" has become something that happens a lot without user interference, presumably "RequestEngGridUpdate"
0x4c821d3c:0x1b, documented as "ClimbDivePacket", seems to have become "TogglePerspectivePacket"
0x4c821d3c:0x1c is NOT the new number for ClimbDivePacket - current details TBC (Might be ActivateUpgradePacket?)
0x4c821d3c:0x1d "FighterLaunchPacket" is the new "ClimbDivePacket"
0x4c821d3c:0x1e is now "FighterLaunchPacket"
0x4c821d3c:0x1f seems to be fighter shooting, probably Shooting Ship ID, Shot Ship ID.
Grrrrrrrrrrrr   :laughing:

**Comment by NoseyNick** [comment]
Come to think of it...
0x4c821d3c:0x16 used to be SetShipSettings before V2.4
0x4c821d3c:0x17 became SetShipSettings in V2.4
HOWEVER, I've seen EMPTY 0x4c821d3c:0x17 in earlier versions. Looking in context, I'm FAIRLY sure this used to be "Reset all Eng coolant to defaults" (double spacebar), So presumably:
0x4c821d3c:0x16 became something else (but I've not seen what), or perhaps was genuinely obsoleted when SetShipSettings got "upgraded"?
0x4c821d3c:0x16 moved to 0x4c821d3c:0x17 for SetShipSettings
0x4c821d3c:0x17 moved to 0x4c821d3c:0x18 for what I shall call "EngResetCoolants" (no params).
0x4c821d3c:0x18 moved to 0x4c821d3c:0x19 for HelmToggleReverse
0x4c821d3c:0x19 moved to 0x4c821d3c:0x1a for RequestEngGridUpdate
0x4c821d3c:0x1a moved to 0x4c821d3c:0x1b for TogglePerspectivePacket
0x4c821d3c:0x1c ... TBC, not sure I've ever seen it.
0x4c821d3c:0x1b moved to 0x4c821d3c:0x1d for ClimbDivePacket
0x4c821d3c:0x1d moved to 0x4c821d3c:0x1e for FighterLaunchPacket
0x4c821d3c:0x1f seems to be fighter shooting, probably Int Shooting Ship ID, Int Shot Ship ID
0x4c821d3c:0x20 not seen
0x4c821d3c:0x21 SingleSeatSelect as described above
0x4c821d3c:0x22 WeapSetBioSignal as (poorly) described above

**Comment by NoseyNick** [comment]
0x4c821d3c:0x04 is "ToggleShields" (by pressing the on-screen toggle button). You already know this, BUT:
0x4c821d3c:0x05 is "ShieldsUp" (by pressing keyboard "K")
0x4c821d3c:0x06 is "ShieldsDown" (by pressing keyboard "L")
Payloads for all of the above appears to be a single integer 0

Artemis experts always prefer K/L to avoid both helm and weapons toggling when the captain orders "Shields up!" or whatever   :-)

**Comment by NoseyNick** [comment]
0x4c821d3c subtype 0x22 explored:

BioBeaconControl packet, introduced around version 2.6.204beta, confirmed present in 2.6.3 to be released at Armada

Subtype (Int), always 0x22
Unknown: (Int), always 12345(?)
Beacon type (byte). 0='Typhon', 1='Whale', 2='Shark', 3='Dragon', 4='Pira', 5='Charybdis', 6='Nsect' (approx "Creature Type" enumeration if "Typhon" == "Classic monster" and wrecks aren't included?)
Direction (byte) enumaration. 0='attract', 1='repel'

version 2.6.204 / 2.6.3 expand the ordnance enumeration:
Homing => 0, Nuke   => 1, Mine   => 2, EMP    => 3,
PShock => 4, Beacon => 5, Probe  => 6, Tag    => 7,

The ordnance selection has been changed in the UI to be accordian-style.

Selecting type 5 "Beacon" enables the "Bio Beacon Control", which sends the above packets to program the beacon. The beacons are launched out the rear of the ship, a lot like mines. They will attract or repel the chosen creature type, for some period of time (TBC) until they run out of energy. They can also be collected again, a lot like anomalies.

Type 6 Probes are like missiles that shoot straight out the front, and keep going in that direction until they vanish off the edge of the map. They scan ships that they pass (somewhat like Science scans, single or sometimes double-scans)

Type 7 Tags are less clear. Further research is required.

**Comment by rjwut** [comment]
To simplify tracking of work, could we track each subtype in a separate issue?

**Comment by NoseyNick** [comment]
0x4c821d3c:0x04 ToggleShields been in docs for ever
0x4c821d3c:0x05 ShieldsUp (by pressing "K") done - thanks @dthaler 
0x4c821d3c:0x06 ShieldsDown (by pressing "L") done - thanks @dthaler 

0x4c821d3c:0x1e FighterLaunchPacket already documented.
0x4c821d3c:0x1f FigherShoot moved to #102
0x4c821d3c:0x20 hypothesized. Worth a ticket? #114
0x4c821d3c:0x21 SingleSeatSelect moved to #100
0x4c821d3c:0x22 BioBeaconControl moved to #101

So assuming I didn't miss any, consider "each subtype in a separate issue" and feel free to close #78 ?
