### ISSUE TITLE
Investigate generic mesh packet

### ISSUE THREAD

**Issue by IvanSanchez** [artemis-nerds/protocol-docs#8]
We are currently unsure of how the generic mesh packet works, specially regarding 8-byte-long fields and the bitmask for the mesh/texture filenames.

Captures of that packet will be appreciated.

**Comment by rjwut** [comment]
Agreed. My feeling is that there aren't any values in the Artemis universe large enough to require a long to store them, so the two fields in question in GenericMeshPacket are probably two ints or floats controlled by the same bit flag rather than longs. Either that, or they're not actually 8 bytes.

**Comment by UserMcUser** [comment]
Below is a generic Mesh packet I captured; the bit-mask looks like "ff ff ff 03" so it would seem to have all of the fields.

ef be ad de 8b 01 00 00 01 00 00 00 00 00 00 00 77 01 00 00 f9 3d 80 80 0e 68 09 00 00 ff ff ff 03 00 50 43 47 00 00 16 c4 00 50 43 47 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 64 be 3c 3a 00 00 00 00 00 00 00 00 6f 12 83 3b 0c 00 00 00 55 00 6e 00 61 00 6b 00 61 00 6c 00 68 00 61 00 69 00 20 00 35 00 00 00 3b 00 00 00 64 00 61 00 74 00 5c 00 4d 00 69 00 73 00 73 00 69 00 6f 00 6e 00 73 00 5c 00 4d 00 49 00 53 00 53 00 5f 00 41 00 72 00 64 00 65 00 6e 00 74 00 5f 00 43 00 72 00 79 00 5f 00 49 00 6e 00 5f 00 54 00 68 00 65 00 5f 00 44 00 61 00 72 00 6b 00 5c 00 6d 00 73 00 68 00 5c 00 50 00 6c 00 61 00 6e 00 65 00 74 00 32 00 30 00 31 00 2e 00 64 00 78 00 73 00 00 00 37 00 00 00 64 00 61 00 74 00 5c 00 4d 00 69 00 73 00 73 00 69 00 6f 00 6e 00 73 00 5c 00 4d 00 49 00 53 00 53 00 5f 00 41 00 72 00 64 00 65 00 6e 00 74 00 5f 00 43 00 72 00 79 00 5f 00 49 00 6e 00 5f 00 54 00 68 00 65 00 5f 00 44 00 61 00 72 00 6b 00 5c 00 74 00 78 00 74 00 5c 00 77 00 61 00 74 00 65 00 72 00 2e 00 70 00 6e 00 67 00 00 00 00 80 3b 45 00 00 00 b0 40 00 00 00 00 00 00 80 3f 00 00 00 00 00 00 80 bf 00 00 80 bf 52 02 00 00 00 20 00 00 00 02 00 00 00 20 00 00 00 00 00 00 00

**Comment by rjwut** [comment]
The tricky part is that there are so many unknowns, that it's hard to tell which lengths are accurate. The packet structure docs were originally created based on my inspection of the ArtClientLib source when I picked up the project, and updated whenever I discovered a problem. The only way to determine the length of any one field is to either notice which bytes change in response to an event and understand why, or figure out how to cause packets to be emitted that separate fields that were previously always observed together. It'll probably require us to fiddle around a lot with generic meshes in a custom mission.

Here's my breakdown of the packet listed above based on our current knowledge of the protocol, and my observations:

`ef be ad de`
`8b 01 00 00`
`01 00 00 00`
`00 00 00 00`
`77 01 00 00`
`f9 3d 80 80`
Preamble identifying an object updating packet.

`0e`
Generic mesh. This appears to be from a 2.1+ packet. Also, the documentation indicates that this is an int, but here it's a byte. Were the docs wrong, or did this change recently?

`68 09 00 00`
Object ID

`ff ff ff 03`
All known fields present.

`00 50 43 47`
`00 00 16 c4`
`00 50 43 47`
Coordinates

`00 00 00 00`
Unknown

`00 00 00 00`
Unknown

`00 00 00 00` `00 00 00 00`
Unknown. This is the first supposed long value.

`00 00 00 00`
Unknown

`64 be 3c 3a`
Unknown. The docs suggest that it's an int, but looking at the given value, I suspect it's actually a float (int value is 977059428, float value is 0.0007200001273304224)

`00 00 00 00`
Unknown

`00 00 00 00` `6f 12 83 3b`
Unknown. This is the second supposed long value, but looking at the bytes, I'm pretty confident that it's not a long. The second half is 998445679 as an int and 0.004000000189989805 as a float. This might be two float fields bound to a single bit flag. Alternatively, it might be that the first half actually corresponds to a different bit.

`0c 00 00 00 55 00 6e 00 61 00 6b 00 61 00 6c 00 68 00 61 00 69 00 20 00 35 00 00 00`
Object name

`3b 00 00 00 64 00 61 00 74 00 5c 00 4d 00 69 00 73 00 73 00 69 00 6f 00 6e 00 73 00 5c 00 4d 00 49 00 53 00 53 00 5f 00 41 00 72 00 64 00 65 00 6e 00 74 00 5f 00 43 00 72 00 79 00 5f 00 49 00 6e 00 5f 00 54 00 68 00 65 00 5f 00 44 00 61 00 72 00 6b 00 5c 00 6d 00 73 00 68 00 5c 00 50 00 6c 00 61 00 6e 00 65 00 74 00 32 00 30 00 31 00 2e 00 64 00 78 00 73 00 00 00`
Mesh file path

`37 00 00 00 64 00 61 00 74 00 5c 00 4d 00 69 00 73 00 73 00 69 00 6f 00 6e 00 73 00 5c 00 4d 00 49 00 53 00 53 00 5f 00 41 00 72 00 64 00 65 00 6e 00 74 00 5f 00 43 00 72 00 79 00 5f 00 49 00 6e 00 5f 00 54 00 68 00 65 00 5f 00 44 00 61 00 72 00 6b 00 5c 00 74 00 78 00 74 00 5c 00 77 00 61 00 74 00 65 00 72 00 2e 00 70 00 6e 00 67 00 00 00`
Texture file path

`00 80 3b 45`
Unknown. The int value is 1161527296, float value is 3000.0, so this pretty certainly a float, not an int as documented.

`00 00`
Unknown

`00`
Unknown

`b0 40 00 00`
`00 00 00 00`
`80 3f 00 00`
RGB color

`00 00 00 00`
Forward shields

`80 bf 00 00`
Aft shields

`80 bf 52 02`
Unknown. The int value is 38977408, float value is 0.00007221853593364358. Probably a float.

`00 00 00 20`
`00 00 00 02`
`00 00 00 20`
`00 00 00 00`
Four unknowns. Given the pattern we're seeing here, I'm wondering if we're off by one or three bytes here.

`00 00 00`
Leftover bytes. If this was one byte long or four bytes long, I would consider it to be an array terminator. As it is, I believe this indicates that previous fields are misaligned.

**Comment by rjwut** [comment]
~~Note that this may have changed now with Artemis version 2.2.0, as there are now multiple types of monsters. Unknown at this time if the generic update packet still handles monsters, and if so, how it will have changed in order to handle the new monster type field.~~ Oops, this is not relevant to this issue.

**Comment by chrivers** [comment]
GenericMesh was indeed very tricky, and the existing guesses were wrong in several places (at least for version 2.4.0). Here's a much improved version of genericmesh:

https://github.com/chrivers/isolinear-chips/blob/master/protocol/objects.stf#L216-L304

**Comment by NoseyNick** [comment]
Further updates to mesh type: Playing 2.6.0 and GENERALLY agreeing with @chrivers 's definition except:
bit 1.7 is a FLOAT, roll
bit 1.8 is a float, pitch (agreeing with @chrivers here)
bit 2.1 is a FLOAT, angle, Corresponds to "angle" in the script file that was in use.

Sure enough, we see some objects with a roll_delta=5 on some meshes where roll (bit 1.7) increases by approx 5.0 per second. It should be noted that they are NOT constrained 0 to 360 or 0 to 2pi or anything, we have seen roll increase 0.0 to 11819.98

bit 4.1 is a STRING, we have seen " " (0x00000002 0x0020 0x0000)
bit 4.2 is a STRING, we have seen " " (0x00000002 0x0020 0x0000)

No idea what these strings ARE, but note that mission-file-docs.txt allows setting hullRace and hullType strings on genericMeshes, so suspect they correspond to those (UNPROVEN)

Oh, and thanks to my 13-year-old reverse-engineer son Aiden for helping me with the details of these bits   :+1:

**Comment by NoseyNick** [comment]
Not tested in 2.7 (which brings ability to scan meshes, I believe), but my 2.6 GenericMesh looks like...

### Object Type 0x0e GenericMesh
  X (bit 1.1, float)
  Y (bit 1.2, float)
  Z (bit 1.3, float)
  Unknown14 (bit 1.4, int)
  Unknown15 (bit 1.5, int)
  Unknown16 (bit 1.6, int)
  roll (bit 1.7, float)
  pitch (bit 1.8, float)
  angle (bit 2.1, float)
  roll_delta (bit 2.2, float)
  pitch_delta (bit 2.3, float)
  angle_delta (bit 2.4, float)
  Name (bit 2.5, string)
  MeshFile (bit 2.6, string)
  TextureFile (bit 2.7, string)
  push_radius (bit 2.8, float)
  block_shot_flag (bit 3.1, byte)
  artscale (bit 3.2, float)
  R (bit 3.3, float)
  G (bit 3.4, float)
  B (bit 3.5, float)
  ForeShields (bit 3.6, float)
  AftShields (bit 3.7, float)
  Unknown38 (bit 3.8, byte)
  Unknown41 (bit 4.1, string)
  Unknown42 (bit 4.2, string)
