### ISSUE TITLE
dat/vesselData.xml topspeed performance data

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#84]
Starry#4197 on discord tells me...

> The Artemis protocol document [specifically the section on Vessel Data in dat/vesselData.xml ] seems to be missing topspeed out of performance data
> The number seems to be impulse speed in 1/100th of a second
> Aka *100 and you get the amount moved in 1s
> Aka *1000 and you get movement at warp 1 in 1 second
> stop watch timing seems to imply this is the correct comparison for Artemis game units to vessel data units
> Acceleration curve - you don't hit top speed immediately so top speed is top speed unsure where the game gets acceleration from
> some of the numbers I checked vs are very old - if its going to be updated it probably wants to be double checked or one of the "we think it is" type tags

Feel free to discuss a bit here if you need further clarification, I'll act as go-between   :-)

**Comment by rjwut** [comment]
Not totally clear on the description of the value of the topspeed attribute, but the fact that it exists is now documented.
