### ISSUE TITLE
Communication with enemy bases in v2.3.0

### ISSUE THREAD

**Issue by rjwut** [artemis-nerds/protocol-docs#85]
Starting with v2.3.0, if COMMs attempts to contact an enemy base, the only message they can send is "Cease operation." (The base will not comply.) This raises some questions:

1. Has the `0x02` value for the [comms target type enumeration](https://artemis-nerds.github.io/protocol-docs/#enum-comm-target-type) been split into friendly and enemy values, or does it still send `0x02` for both enemy and friendly bases?
2. What is the [message value](https://artemis-nerds.github.io/protocol-docs/#enum-comm-message) for "Cease operation"?

**Comment by NoseyNick** [comment]
One data point:
4b4c4c57020000004f0500000000000074002f0072006f00 # 2.6.0 payload

Which I translate as...
commsMessage(2,1359,0, 116,47,114,111);
type=2 # station
to=1359 "Kralien base 1"
msg=0 # so yes, message 0 is "cease operation"?
target=116 # probably junk
unk5=47 # probably junk
unk6=114 # probably junk
unk7=111 # probably junk

Response:
commText(16,UTF16("Kralien Base 1 Kralien Base").UTF16("We don't listen to you, Artemis.  Go away."));

Need me to enumerate a bunch of other message types?

**Comment by rjwut** [comment]
As long as 3 is still "other" (as I'm sure it probably is) I think we're okay. I've gone ahead and updated the docs.

**Comment by NoseyNick** [comment]
```
# To player, Intepid, "yes" [111]:
commsMessage(0,1017,0, 116,47,114,111);
# To player, Intepid, "no" [112]:
commsMessage(0,1017,1, 116,47,114,111);
# To player, Intepid, "help!" [113]:
commsMessage(0,1017,2, 116,47,114,111);
# etc etc
# enemy, #1, will you surrender [211]:
commsMessage(1,1025,0, 116,47,114,111);
# enemy, #1, hey wormface... [212]:
commsMessage(1,1025,1, 116,47,114,111);
# [enemy] base, #1, cease operations... [311]:
commsMessage(2,1022,0, 116,47,114,111);
# other ship, #1, hail... [411]:
commsMessage(3,1041,0, 116,47,114,111);
# other ship, #1, go defend, enemy base 1... [41?1]:
commsMessage(3,1041,9, 1022,0,114,111);
# other ship, #1, adjust course, bearing 0 ... [41?2]:
commsMessage(3,1041,1, 1022,0,114,111);
# other ship, #1, adjust course, bearing 90 ... [41?3]:
commsMessage(3,1041,2, 1022,0,114,111);
# other ship, #1, adjust course, bearing 180 ... [41?4]:
commsMessage(3,1041,3, 1022,0,114,111);
# other ship, #1, attack nearest enemy ... [418]:
commsMessage(3,1041,7, 1022,0,114,111);
# other ship, #1, proceed to your destination ... [419]:
commsMessage(3,1041,8, 1022,0,114,111);

I encode the values as...
int JamCRC("commsMessage") /* ==0x574c4c4b */
int int int, short short short short
```
... though I can see why you think int int int int int, which also works as long as the last one is junk, and the penultimate one is junk except when it's a target objid.
Curious as to what that UTF16-looking junk might be, I see "t/ro", which could be part of either of these strings I found in the .exe:
"da**t/ro**undBullet.png"
"Every game (even games with multiple bridges and spaceships) needs just one server.  Since all clients connect to it, it should have a fast interne**t/ro**uter connection.  The server is also always the main screen for the bridge of the first ship."

**Comment by NoseyNick** [comment]
My parser.pl (somewhat unofficially available at http://noseynick.org/artemis/ ) now treats the args as 5 ints despite frequently "smelling like" 3 ints 4 shorts. It also adds human-readable comments like:
```
commsMessage(1,1236,0, 3080308,7274610); # enemy 1236 Will you surrender?
commsMessage(1,1236,1, 3080308,7274610); # enemy 1236 Taunt #1
commsMessage(1,1236,2, 3080308,7274610); # enemy 1236 Taunt #2
commsMessage(1,1236,3, 3080308,7274610); # enemy 1236 Taunt #3
commsMessage(2,1017,0, 3080308,7274610); # station 1017 Stand by for docking (friend) OR Cease operation (foe)
commsMessage(2,1017,1, 3080308,7274610); # station 1017 Please report status.
commsMessage(2,1017,2, 3080308,7274610); # station 1017 Build homing missiles
commsMessage(2,1017,3, 3080308,7274610); # station 1017 Build nukes
commsMessage(2,1017,4, 3080308,7274610); # station 1017 Build mines
commsMessage(2,1017,5, 3080308,7274610); # station 1017 Build EMPs
commsMessage(2,1017,6, 3080308,7274610); # station 1017 Build PShocks
commsMessage(3,1216,0, 3080308,7274610); # other 1216 Hail
commsMessage(3,1216,1, 1017,7274610); # other 1216 Turn to heading 0
commsMessage(3,1216,4, 1017,7274610); # other 1216 Turn to heading 270
commsMessage(3,1216,5, 1017,7274610); # other 1216 Turn L 10 degrees
commsMessage(3,1216,7, 1017,7274610); # other 1216 Attack nearest enemy
commsMessage(3,1216,8, 1017,7274610); # other 1216 Proceed to your destination
commsMessage(3,1216,9, 1017,7274610); # other 1216 Go defend [1017]
commsMessage(3,1216,15, 1017,7274610); # other 1216 Turn L 25 degrees
```

**Comment by NoseyNick** [comment]
I should confirm whether or not 2.6.3 brings new comms commands for "build new Beacons / Tags / Probes"

**Comment by NoseyNick** [comment]
Confirmed! v2.6.3 (or probably 2.6.20X-beta) adds:
```
commsMessage(2,1017,7, 6881312,7602286); # station 1017 build beacons
commsMessage(2,1017,8, 6881312,7602286); # station 1017 build probes
commsMessage(2,1017,9, 6881312,7602286); # station 1017 build tags
```
Translation: add to your COMM Message /  To stations:

0x07 | Build Beacons
0x08 | Build Probes
0x09 | Build Tags
