### ISSUE TITLE
v2.6.3: Beacons, probes, and tags

### ISSUE THREAD

**Issue by rjwut** [artemis-nerds/protocol-docs#93]
I've updated the [COMM Message](https://artemis-nerds.github.io/protocol-docs/#enum-comm-message) and [Ordnance Type](https://artemis-nerds.github.io/protocol-docs/#enum-ordnance-type) enums to reflect the addition of beacons, probes, and tags to _Artemis_ v2.6.3. I presume that this means that a similar change has been made to the [Weapons Console struct](https://artemis-nerds.github.io/protocol-docs/#object-weapons-console). Can someone confirm this?

**Comment by NoseyNick** [comment]
```
    0x02 => ['WeapCons', # +++ ASSUMING VERSION 2.1.5 or greater:
        Homings=>'C', Nukes=>'C', Mines=>'C', EMPs=>'C',
        PShocks=>'C',
        $PROTOVERSION >  26 ? ( Beacons=>'C', Probes=>'C', Tags=>'C' ) # seen in 2,6,204 and 2,3,0
        :                     ( Unknown16=>'C' ),                      # was previously always 0?
        LoadTime1=>'f<', LoadTime2=>'f<',  LoadTime3=>'f<',
        LoadTime4=>'f<', LoadTime5=>'f<',  LoadTime6=>'f<',
        TubeUsed1=>'C',  TubeUsed2=>'C',  TubeUsed3=>'C',
        TubeUsed4=>'C',  TubeUsed5=>'C',  TubeUsed6=>'C',
        TubeCont1=>'C',  TubeCont2=>'C',  TubeCont3=>'C',
        TubeCont4=>'C',  TubeCont5=>'C',  TubeCont6=>'C',
    ],
```
So the 6 bytes for 5 ordnances have become 8 bytes for 8 ordnances. The "one after pshocks" that seemed to be previously "unused, always 0" has become Beacons, and is followed by 2 new bytes for Probes and Tags.

**Comment by NoseyNick** [comment]
```
f93d808002fd030000ffffff0308020604040404040000000000000000600328ff52062cff460221ff4d022bff00010000000006050605030600000000 # 2.6.3 payload
f93d808002fd030000ffffff030802060404040404000000006fbaf33c6d472aff75502eff774f2dff634224ff0002000000000507464e514500000000 # 2.6.3 payload
f93d808002fd030000ffffff03080206040404040500000000000000006d472aff75502eff774f2dff634224ff0000000000000506464e514500000000 # 2.6.3 payload
f93d808002fd030000ffffff03080206040404040500000000000000006d472aff75502eff774f2dff634224ff0101000000000506464e514500000000 # 2.6.3 payload
f93d808002fd030000ffffff0308020604040504030000000000000000600328ff52062cff460221ff4d022bff00000000000006070605030600000000 # 2.6.3 payload
f93d808002fd030000ffffff0308020604040505050000000000000000600328ff52062cff460221ff4d022bff00000000000006070605030600000000 # 2.6.3 payload
f93d808002fd030000ffffff0308020604040505053d0215ff620527ff600328ff52062cff460221ff4d022bff00000000000002060605030600000000 # 2.6.3 payload
f93d808002fd030000ffffff030802060404050505583b24ff614226ff6d472aff75502eff774f2dff634224ff0000000000003a40464e514500000000 # 2.6.3 payload
```

**Comment by NoseyNick** [comment]
2.6.204-beta or 2.6.3 also bring the 0x4c821d3c subtype 0x22 as discussed in #78 

There's also definitely some new fields in Player Ship Objects, NPC Objects, Creature Objects, presumably to represent that actual tags once the creatures/ships have actually been tagged... but I've not been able to explore these in enough detail yet.

I understand from 2.6.3/mission-file-docs.txt there are supposed to be 4 slots for the 4 tags, with a "sourcetext" (WHO tagged the monster/ship) and a "datetext" (WHEN they tagged the monster/ship). Suspect mission scripting may be the easier way to debug this one rather than reverse-engineering "real games"    😕

**Comment by NoseyNick** [comment]
Weapons Console Object properties, I can confirm that anything AFTER 2.6.0 REMOVES "Unknown (bit 1.6, byte)" (Which as far as I can tell was ALWAYS zero) but extends the "Ordnance counts" to include bytes for...
Homings, Nukes,  Mines, EMPs, PShocks (as before)
Beacons, Probes, Tags (new v2.6.204 / v.2.6.3 ordnances)
Tube (un)load times and every other attribute move up

**Comment by NoseyNick** [comment]
NPCShip Object changes:

Unknown (bit 4.8, float), Unknown (bit 5.1, FLOAT), Unknown (bit 5.2, FLOAT)
These seem to be targetPointX/Y/Z. These are not new for "v2.6.3: Beacons, probes, and tags" but whilst you're there:

AFTER targetPointZ, 2.6.204 / 2.6.3 add "Tagged" (byte) boolean, set to 1 if this ship has been tagged. Simply adds "tag signal detected" to Science scans as far as I can tell.

2.6.3 (but not 2.6.204 beta) then adds Unknown (bit 5.4, byte). SEEMS to always be 0 so far.

The Ship system damages and Beam Frequencies all move up 2 bits.

**Comment by NoseyNick** [comment]
Anomaly Object changes:

After X/Y/Z and Upgrade...

v2.3.0 added some fields - obviously not new for "v2.6.3: Beacons, probes, and tags" but whilst you're there:

Unknown (int) - seen values of 0 and 4
Unknown (int) - always zero?

v2.6.3 (but not 2.6.204beta) adds:

Beacon Type (byte) - see BioBeaconControl as documented in #101 
Beacon Direction (byte) - see BioBeaconControl as documented in #101 

A beacon is dropped out the back of the ship, a lot like a mine. It attracts or repels (Beacon Direction) one particular type of creature (Beacon Type) until it runs out of energy. It can then be collected a lot like any anomaly.

**Comment by rjwut** [comment]
I've updated the weapons console struct. More updates to follow.

**Comment by NoseyNick** [comment]
See also "Creature is wrong" #56 for Creature updates - 2.6.3 adds one unknown byte

**Comment by NoseyNick** [comment]
See also "Creature is wrong" #56 for Creature updates - 2.6.3 adds one unknown byte

**Comment by rjwut** [comment]
Is byte 1.4 present on beacon anomaly objects, and are bytes 1.7 and 1.8 present on non-beacon anomaly objects? And if so, what are their values?

**Comment by NoseyNick** [comment]
Confirmed, discussed on Discord #artemis_development:
field1.4 "Upgrade" on Beacons is 8. I THINK the docs must be referring to "Game world upgrades" here, not "Upgrades". A new "Game world upgrade" type 8 = Beacon would make sense.
field1.7 and 1.8 ARE present on non-beacon anomalies, but values 0,0

**Comment by NoseyNick** [comment]
Can presumably wait for 2.6.3 / 2.7.0 to be released (any day now!) before updating the docs to the latest OFFICIAL protocol version. Keeping up with Betas is HARD   😞

**Comment by NoseyNick** [comment]
See also #108

**Comment by NoseyNick** [comment]
For clarity:

### Object Type 0x08 Anomaly
  X (bit 1.1, float)
  Y (bit 1.2, float)
  Z (bit 1.3, float)
  pickupType (bit 1.4, int)
  Scanned (bit 1.5, int, new in 2.3.0) - bitmask like SingleScan/DoubleScan in ObjNPCShip
  Unknown (bit 1.6, int, new in 2.3.0) - always 0 (?)
  beaconMonsterType (bit 1.7, byte, new in 2.6.3)
  beaconEffect (bit 1.8, byte, new in 2.6.3) 0=Attract, 1=Repel - See BioBeaconControl as documented in #101

### Object Type 0x02 WeapCons
  Homings (bit 1.1, byte)
  Nukes (bit 1.2, byte)
  Mines (bit 1.3, byte)
  EMPs (bit 1.4, byte)
  PShocks (bit 1.5, byte, "new" in 2.2.0 BUT was previously a dummy "always 0")
  Beacons (bit 1.6, byte, new in 2.6.3)
  Probes (bit 1.7, byte, new in 2.6.3)
  Tags (bit 1.8, byte)
  LoadTime1 (bit 2.1, float)
  LoadTime2 (bit 2.2, float)
  LoadTime3 (bit 2.3, float)
  LoadTime4 (bit 2.4, float)
  LoadTime5 (bit 2.5, float)
  LoadTime6 (bit 2.6, float)
  TubeUsed1 (bit 2.7, byte)
  TubeUsed2 (bit 2.8, byte)
  TubeUsed3 (bit 3.1, byte)
  TubeUsed4 (bit 3.2, byte)
  TubeUsed5 (bit 3.3, byte)
  TubeUsed6 (bit 3.4, byte)
  TubeCont1 (bit 3.5, byte)
  TubeCont2 (bit 3.6, byte)
  TubeCont3 (bit 3.7, byte)
  TubeCont4 (bit 3.8, byte)
  TubeCont5 (bit 4.1, byte)
  TubeCont6 (bit 4.2, byte)
