### ISSUE TITLE
Player Ship Object updates

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#94]
Ship number (bit 2.2, int) isn't. It might be "side" or "fleet" or something like that?

Unknown (bit 3.3, short) is a boolean short "Ship is in Nebula". A value of 0 allows any warp speed. A value of 1 limits you to max warp 1. Other values HAVE been observed but MUCH more rarely (and seem to similarly limit max warp 1)

Unknown (bit 5.7, 4 bytes) Seemingly needs to be -1 for player's ship to be shown on Sci / Captain's Map. 0 will make it invisible to those consoles. Other values have been observed MUCH more rarely.

Unknown (bit 5.8, byte, new as of v2.3.0) Seems to be the ship number (0=Artemis, 1=Intrepid, 2=Aegis etc). This probably means it's NOT new in 2.3.0 but we're mistaken about where new fields were inserted into objects. TBC.

New fields:

Beacon Type (bit 6.4, byte, new as of v2.6.3 or possibly 2.6.20X-beta) - If this ship drops a beacon, this is the type of creature that the beacon will attract/repel. Follows ENUM Creature Type, except official names seem to be 0='Typhon', 1='Whale', 2='Shark', 3='Dragon', 4='Pira', 5='Charybdis', 6='Nsect'. Set by Weapons console with BioBeaconControl packet 0x4c821d3c 0x22 discussed in #78 

Beacon Dir (bit 6.5, byte, new as of v2.6.3 or possibly 2.6.20X-beta) - If this ship drops a beacon, 0 means the beacon will ATTRACT the specified creature. 1 means the beacon will REPEL the specified creature. Set by Weapons console with BioBeaconControl packet 0x4c821d3c 0x22 discussed in #78

**Comment by NoseyNick** [comment]
Sorry, credit where credit is due... A lot of the above (all non-beacon stuff) was discovered by Starry in #artemis_development on https://discord.gg/KHBQeEU

**Comment by NoseyNick** [comment]
... and OK, to complicate matters further, looks like Ship number (bit 2.2, int) probably WAS ship number for sufficiently early versions of Artemis   [sigh]

v2.0.0 untested at this time
v2.1.1, bit 2.2, int DID represent ship number 1=Artemis, 2=Intrepid, 3=Aegis etc...
v2.1.5 ditto
v2.2.0 ditto
v2.3.0, bit 2.2, int has become something like "fleet" or "side" or whatever.
v2.3.0, bit 5.8 has become ship number, BUT 0=Artemis, 1=Intrepid, 2=Aegis etc...
v2.4.0 ditto
v2.5.1 ditto
v2.6.0 ditto
v2.6.3 ditto

**Comment by rjwut** [comment]
Docs updated.

**Comment by NoseyNick** [comment]
I'd probably have noted that "In a nebula" limits you to Warp 1...  but 👍 Cheers!
