### ISSUE TITLE
0xf754c8fe subtype 0x00 is KABOOM

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#95]
The docs say:
DestroyObjectPacket2
Type: 0xf754c8fe:0x00 [from server]
"Starting in v2.3, this packet indicates that an object was destroyed"

Believe it had previously been known as "UnknownPreDestroy" or similar?

Should clarify this is NOT the same as 0xcc5a3e30 DestroyObjectPacket JamCRC("objectDelete"), but is in fact the big yellow-orange-and-red fireball KABOOM graphical effect. Personally I'm calling it Kaboom(ObjType(ObjID)).

Obviously enough, a common pattern is...
```
Kaboom(ObjMine(6578));  objectDelete(ObjMine(6578));
Kaboom(ObjNPCShip(6996));  objectDelete(ObjNPCShip(6996));
Kaboom(ObjMine(6577));  objectDelete(ObjMine(6577));
```
... but if you inject it in server2client traffic, you can make anything go Kaboom (on mainscreen or observer) without actually being destroyed - it's JUST the pretty graphical effect   😁

**Comment by rjwut** [comment]
DestroyObjectPacket2 renamed to ExplosionPacket in the protocol docs.
