### ISSUE TITLE
Torpedo object - some details

### ISSUE THREAD

**Issue by NoseyNick** [artemis-nerds/protocol-docs#96]
Torpedo (object type 0x0b)
Bit field (2 byte) - there is then no Unknown (byte).
See  #75 - 2 bytes for an 8-item bitfield is normal.

X coordinate (bit 1.1, float) - The torpedo's location on the X axis.
Y coordinate (bit 1.2, float) - The torpedo's location on the Y axis.
Z coordinate (bit 1.3, float) - The torpedo's location on the Z axis.

Delta X (bit 1.4, float) - from -1.0 to 1.0.
Delta Y (bit 1.5, float) - from -1.0 to 1.0.
Delta Z (bit 1.6, float) - from -1.0 to 1.0.

Unknown (bit 1.7, int) - Always 11. We think. Which happens to be 0x0b which is the same as "Torpedo" object type, but that seems overly-redundant, no?

Ordnance Type (bit 1.8, int) as per Ordnance Type ENUM:
    Homing => 0, Nuke   => 1, Mine   => 2, EMP    => 3,
    PShock => 4, Beacon => 5, Probe  => 6, Tag    => 7,

**Comment by rjwut** [comment]
Docs updated.
