### ISSUE TITLE
Should vesselData docs be moved to artemiswiki.pbworks.com

### ISSUE THREAD

**Issue by dthaler** [artemis-nerds/protocol-docs#98]
The rationale for moving vesselData out of the protocol docs page and over to the Artemis wiki is:
1) The audience is different.  Protocol documentation is really for people who write code, which is relatively a small set of people.  The vesselData docs on the other hand are needed by simple modders who don't write code, similar to the docs on artemis.ini (http://artemiswiki.pbworks.com/w/page/52887517/artemis%20ini).
2) It isn't inherently part of the "protocol" since it doesn't appear on the wire.

**Comment by rjwut** [comment]
Issue #3 asked for this documentation to be included. Yes, they're not network protocols but they are file protocols, ones that devs might want to parse, so it was felt that they were relevant. However, you are right that the network protocol is only of use to developers, while the other protocols are useful to non-coding modders. I'd like to open this question up to others and ask what they think.

**Comment by NoseyNick** [comment]
I certainly valued finding the SNT file details in protocol-docs. vesselData, not sure.

Dunno, if vesselData is BETTER documented elsewhere, protocol-docs should AT LEAST have a "Links to other useful Artemis-Nerds data" or something

There's certainly something to be said for "one big single HTML file you can download and keep for offline use when coding on the bus/plane/tent/etc"   😆

**Comment by NoseyNick** [comment]
There's also quite a few bits of the on-the-wire protocols that heavily REFERENCE vesselData.xml - Ship IDs, beam port indexes, factions, special abilities, hullRace, broadType, etc...

**Comment by dthaler** [comment]
There's also quite a few places (e.g., mission scripting docs) on the wiki that heavily reference vesselData.xml.

**Comment by dthaler** [comment]
So far I find the reasons for moving it to the wiki more compelling, with a simple cross reference from the protocol docs as NoseyNick suggested.
